- KerbalStuff/email.py
- emails/confirm-account
Should probably be tested first, as I don't have the mailer working in Docker...
> Make site-name from config be used in the confirmation email

- requirements.txt
Looks like this was causing pip to install the wrong version of bcrypt on a fresh install, IE Docker.
@godarklight
> Removing unnecessary py-bcrypt package

- README_DOCKERFILE.md
- docker-compose.yml
- docker/start.sh
This is needed because Gunicorn workers seem to have a bad habit of not seeing new static files when they are processed on the first request, forcing you to refresh the page twice everytime you make a change there.
> Toggle between flask debug and gunicorn in docker

- KerbalStuff/config.py
- app.py
- docker-compose-deploy.yml
- docker/deployment_settings.cfg.example
- docker/nginx/Dockerfile
- docker/nginx/sites-enabled/spacedock.conf
To make this deploy onto a server, you'd need some sort of proxy serving passing connections to the nginx container on 22075. The nginx container will take care of serving /content and /static and will pass everything else onto the spacedock container.
To get this to be deployed, you'd have to run (assuming inside a Jenkins job):
```
docker build --file $WORKSPACE/Dockerfile --tag spacedock.info:5550/spacedock:$GIT_COMMIT --tag spacedock.info:5550/spacedock:latest $WORKSPACE
docker build --file $WORKSPACE/docker/nginx/Dockerfile --tag spacedock.info:5550/nginx:$GIT_COMMIT --tag spacedock.info:5550/nginx:latest $WORKSPACE/docker/nginx
docker push spacedock.info:5550/spacedock
docker push spacedock.info:5550/nginx
docker-compose --file $WORKSPACE/docker-compose-deploy.yml --project-name …
```
> Create a docker-compose for deployment

- emails/mod-updated
Right now the username doesn't display, since the username token isn't formatted properly. Messages arrive reading like:
"Hi there!  has just published version"
> Fix username in message body for mod updates

- docker-compose-deploy.yml
There were weird port issues in docker that caused the port to be closed and nginx to give out a 502. Seems that using only one postgres container fixes this.
> Use only one postgres container, because of port weirdness

- KerbalStuff/ckan.py
NetKAN has been receiving a number of SpaceDock pull requests with license strings that don't match what CKAN uses. This happens for the various Creative Commons licenses; SpaceDock uses a space after the CC, while CKAN expects a hyphen.
Latest example here ("CC BY-NC-SA 3.0" vs "CC-BY-NC-SA-3.0"):
- https://github.com/KSP-CKAN/NetKAN/pull/6094
- https://ci.ksp-ckan.org/job/NetKAN/6608/consoleText
This pull request replaces all spaces in a license string to be sent to CKAN with hyphens.
> Stop sending spaces in licenses to CKAN

- Dockerfile
- config.ini.example
- db_initialize.py
- docker-compose-deploy.yml
- docker-compose.yml
- docker/start_celery.sh
Problem
-------
The Docker container is not runnable in the current state.
It is also based on Ubuntu 14.04, which isn't supported any more since this April.
Solution
-------
* Change `FROM ubuntu:14.04` to `FROM ubuntu:latest` to pull the latest LTS (currently 18.04).
* Install `sudo`, `netcat` and `default-libmysqlclient-dev` packages.
* Update NodeJS download source (old one is deprecated)
* Change `coffe-script` to `coffescript`, old npm package is deprecated.
* Some more small adjustments
> Fixes for Docker

- KerbalStuff/blueprints/api.py
Mod authors sometimes delete and replace a version of a mod with a new download. If such a version has already been indexed by an external service (such as CKAN's bot), there's no way to know this has happened (ignoring active notifications for the moment).
This can cause problems for CKAN, since it tracks hashes to ensure that the file the user downloads is the same one the CKAN bot indexed. In KSP-CKAN/CKAN#2337 we implemented a strategy that solved this for GitHub using the release creation timestamp, but the same has not been possible for SpaceDock because the timestamp is unknown.
Now the mod version API returns a `"created"` property containing the timestamp when that version was created, in ISO8601 format. This value is already part of the `ModVersion` data object: …
> Return mod version creation datetime in API

- KerbalStuff/blueprints/api.py
- requirements-backend.txt
- templates/view_profile.html
**Depend on psycopg2-binary instead of building it from source:**
---
There is a non-Python dependency for building the package from source, an error is thrown trying to do `pip3 install -r requirements-backend.txt`.
To solve this, use the binary package instead.
**Fix ckan notification in API:**
---
The API _tried_ to always send new mods to ckan after creation, even if not requested by the mod author. Now it checks for the tag before doing so.
Also, it didn't work at all, because `send_to_ckan()` has to be used for new mods. `notify_ckan` is only for updated mods.
Also check whether `mod.ckan` is set before notifying it after updates via the API.
**Add missing closing tags for two spans in view_profile.html:**
---
To be precise, in the administrator code section.
> Fix backend dependencies and CKAN notifications in API

- KerbalStuff/blueprints/api.py
The current endpoint, https://alpha.spacedock.info/api/games, returns an HTML page, when it should be returning a JSON file. The publishers endpoint (https://alpha.spacedock.info/api/publishers) doesn't use `json.dumps()` and actually returns a JSON file.
If it's indeed broken like the comment I removed said it was, I suggest we merge this so we can figure out why returning a JSON object is broken for this endpoint.
> Stop using json.dumps for /api/games

- KerbalStuff/app.py
- KerbalStuff/config.py
- config.ini.example
- templates/layout.html
Motivation
---
The footer was missing links to the Discord and Riot channels.
By adding more entries for each link, I realised that it will be a lot better to maintain if there's just one config entry for all of them.
If a new channel comes up, or an old one goes away, there's only a single change needed (well or two, if you count the `config.ini.example`) instead of 3 (4).
Changes
---
This deletes the old `'IRC-channel'` config entry, and instead creates a new one called `support-channels`, which should be a dictionary, where the key is the link text and the value is the link URL.
To parse the dictionary string to a dict object, `ast.literal_eval()` is used. I read somewhere this should be safe, as long as the string is not a few thousand chars long or something.
This method is called …
> Make support server/channel links in footer dynamic

- templates/create.html
Currently when you create a mod, you get this message:
However, the red text does not reflect current intentions; @V1TA5 said this on IRC:
> i think of flag and texture mods not as real mods (for me a mod has to contain code). but i decided to tollerate gfx mods (textures,flags,etc) because its strictly still modifying the game and SD should thus offer hosting for them.
Now the red text about craft files and flag packs no longer mentions flags, and indicates that craft files should be uploaded to KerbalX.
(Let's hold off on merging this until we're ready to test the web hook again.)
> Allow crafts and flags

- KerbalStuff/app.py
- KerbalStuff/config.py
After #234 got pulled to alpha, the server started returning status 500 errors:
```
Aug 28 10:58:11 sd6 gunicorn[16884]: 2019-08-28 10:58:11,198 ERROR Backend:16891 Exception on / [GET]
Aug 28 10:58:11 sd6 gunicorn[16884]: Traceback (most recent call last):
Aug 28 10:58:11 sd6 gunicorn[16884]:   File "/usr/lib/python3.6/configparser.py", line 789, in get
Aug 28 10:58:11 sd6 gunicorn[16884]:     value = d[option]
Aug 28 10:58:11 sd6 gunicorn[16884]:   File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.6/collections/__init__.py"
Aug 28 10:58:11 sd6 gunicorn[16884]:     return self.__missing__(key)            # support subclasses that define __missing__
Aug 28 10:58:11 sd6 gunicorn[16884]:   File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.6/collections/__ini …
```
> Gracefully handle missing config

- KerbalStuff/blueprints/api.py
For newly uploaded mod releases, the `download_path` also saved in the database is set to the absolute path (`/srv/storage/...`), instead of the relative path inside the `storage_path`.
This path is later used to dynamically generate the links to download mods, and this is leading to 404s due to the wrong path:
`GET https://spacedock.info/content//srv/storage/kspmods/DasSkelett_3/Super_Awesome_Test_Mod/Super_Awesome_Test_Mod-1.5.zip`
This happened somewhere in the big refactor, the path has been combined inline before:
`version = ModVersion(secure_filename(version), game_version_id, os.path.join(base_path, filename))`
`_save_mod_zipball()` now returns the relative path again, which is then saved in the database via `ModVersion()`.
> Fix download_path being saved absolute in the database

- KerbalStuff/blueprints/api.py
There's a check for validity of the uploaded zip I overlooked in #252.
This PR should address this. `_save_mod_zipball` now returns a tuple of `(full_path, relative_path)`, and the corresponding one is used where it is needed.
> Use full path to check zip validity

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/ckan.py
CKAN is receiving mod indexing requests for unpublished mods, which are then updated at publish. KSP-CKAN/NetKAN#7896:
Unpublished mods aren't supposed to be revealed to the world in any way, and CKAN's validation checks won't work until publish.
In #231 a `notify_ckan` call in `create_mod` was changed to `send_to_ckan`. `notify_ckan` did not make sense because it only works for mods that are already indexed. However, `send_to_ckan` **still** doesn't make sense because a mod at this point is not published, and all other usages of this function check `mod.published`. `create_mod` as currently written cannot validly trigger _any_ CKAN events. However, in principle it is possible that at some point in the future `create_mod` might also set a mod as published, if such a change was worked on. …
> Check if mod is published in CKAN triggers

- Dockerfile
- KerbalStuff/blueprints/api.py
- frontend/Dockerfile
- frontend/coffee/update.coffee
Currently most of the errors you can encounter while/after uploading mods are "swallowed".
These are for example problems saving a zipball due to the reoccurring storage problem, an invalid zipfile, internal server errors and so on.
What happens now is that error messages are actually returned by the server/api, but the client/frontend is not able to display them (or better, throws an exception trying to display them), and thus the frontend stays in an incomplete state, where the user can't see what actually happens or already happened behind the scenes. It appears to load infinitely, as often reported in the forums.
The JavaScript code is re-ordered to
first check if there's a valid JSON response by the server,
a) if yes, check if result.error is false
a.a) if yes, everything's fine! …
> Catch and display upload errors

- KerbalStuff/blueprints/profile.py
- templates/mod-box.html
Currently, if for some, theoretically impossible, reason a mod of an author has no `default_version`, viewing their profile results in a 500.
(If the mod is still unpublished, it only results in a 500 for the author)
The cause of the error are the mod boxes, that are accessing `mod.default_version.gameversion` to display the `For ...` message in the corner. If `mod.default_version` is `None`, an exception is thrown.
`mod-box.html` checks if `mod.default_version` is `None`, and if so, displays an `-` instead of the KSP version.
Also the flask route is enhanced to also show unpublished mods to admins.
There are still many other places left where we are accessing `mod.default_version` without null-checks, for example the mod page itself.
They have to be fixed separately, which is more work. …
> Don't break profile page if a mod has no default_version

- frontend/coffee/global.coffee
- templates/featured-mod-box.html
- templates/mod.html
- templates/mod_list.html
A forum user reported problems seeing the follow button on the mod page.
In a PM they said they are using Adblock Plus on Firefox.
Downloading the extension and activating the `Block social media icons tracking` option confirmed the problem:
ABP uses a list called ["Fanboy's Social Blocking List"](https://easylist-downloads.adblockplus.org/fanboy-social.txt) if the `Block social media icons tracking` is activated. That one includes filters that probably cause a lot of false positives, and in our case it's `##.follow-button` that triggers.
Rename the `.follow-button` class to `.follow-mod-button` (and `.unfollow-button` to `.unfollow-mod-button` to stay consistent).
Local testing shows that it brings the follow button back.
VITAS mentioned there were also reports of the download button …
> Work around over-eager adblockers hiding stuff they shouldn't hide

- KerbalStuff/blueprints/api.py
As noted in Discord during review of KSP-CKAN/CKAN#3059, the timestamps from #195 don't indicate timezones. Technically this means they're in "local" time, whatever that means for a server/client interaction.
We just return `created` from the database, which is generated by `datetime.now`, which does not include the timezone:
https://github.com/KSP-SpaceDock/SpaceDock/blob/0e5f6c5f9d64fd071d14bbd722ca8e938e90b0bb/KerbalStuff/objects.py#L230
It's not clear whether the timezone can be saved to the db anyway, though. At least one comment on StackExchange suggested it couldn't. So we can add it at load instead.
Now we set the TZ to UTC.
> Send UTC TZ for mod creation timestamps

- .github/FUNDING.yml
The following commits were somehow merged to master after we forked alpha + beta.
```
$ git log --no-merges upstream/old-master ^upstream/master
commit e537e2217f0a64f812aa8c80c21b088fb289fba6
Author: VITAS <github.v@52k.de>
Date:   Sun Jul 28 17:13:15 2019 +0200
Update FUNDING.yml
commit 705ef6c1fb46fd1d24c483bac0fcfd68acf8cc34
Author: VITAS <github.v@52k.de>
Date:   Sun Jul 28 17:11:37 2019 +0200
Update FUNDING.yml
commit cfd519bfce9b4eb40c59d4b87ec8f292a174e34a
Author: VITAS <github.v@52k.de>
Date:   Sun Jul 28 15:49:38 2019 +0200
Set theme jekyll-theme-minimal
commit 83b1d4830656ad7b98dc376238906c4e167b4ca7
Author: VITAS <github.v@52k.de>
Date:   Sun Jul 28 15:48:20 2019 +0200
Create FUNDING.yml
```
The `FUNDING.yml` changes (83b1d4830656ad7b98dc376238906c4e167b4ca7 …
> Restore sponsor button on GitHub

- KerbalStuff/blueprints/admin.py
- templates/admin-blog.html
- templates/admin-email.html
- templates/admin-game-versions.html
- templates/admin-games.html
- templates/admin-links.html
- templates/admin-page-nav.html
- templates/admin-publishers.html
- templates/admin-users.html
- templates/admin.html
- templates/layout.html
The admin page is currently unusable on production, because it requests **all** users and tries to paginate them client-side.
This kills every browser out there.
The admin page, which has been a one-page app with multiple tabs, is broken up in multiple pages, one for each previous tab:
```
@admin.route("/admin/users/<int:page>")
@admin.route("/admin/blog")
@admin.route("/admin/publishers/<int:page>")
@admin.route("/admin/games/<int:page>")
@admin.route("/admin/gameversions/<int:page>")
@admin.route("/admin/email", methods=['GET', 'POST'])
@admin.route("/admin/links")
```
All tables (except the one for links) are now paginated server-side. (This would have been way easier if we used flask-sqlalchemy...)
The number of items per page is hardcoded to 10, I think it would also be possible to …
> Rework the admin area

- docker-compose.yml
- frontend/styles/listing.scss
- frontend/styles/stylesheet.scss
- templates/edit_mod.html
- templates/mod.html
For commit one (`Don't restart containers in development setup`):
Currently the Docker containers restart themselves if you didn't stop them manually even after PC reboots for example. It was quite funny to realize the SD containers started themselves on my PC everyday after about a week of not touching them.
Fro commit two:
The short mod description is currently not shown on the mod page itself. You can only see it if you hover over the mod card on the mod list page. or if you edit the mod.
Commit one:
Change the Docker container restart policy to default (which is "never") in the docker-compose.yml used for development. I think this is the better policy, since if the containers crash, you normally want to investigate what's going on before the containers start automatically again. …
> Show short mod abstract on mod page

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/common.py
- frontend/coffee/create.coffee
- templates/create.html
Noticed the following error in the syslog when navigating to the mod update upload page on alpha:
```
2020-05-22 11:02:31,965 ERROR Backend:30011 Exception on /mod/3/Test download path/update [GET]
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
self.dialect.do_execute(
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
cursor.execute(statement, parameters)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "kerbal-space-program"
LINE 3: WHERE game.id = 'kerbal-space-program' ORDER BY game.id DESC...
<some more messages and lines and stuff>
File …
```
> Fix default game fallback in _restore_game_info

- KerbalStuff/blueprints/api.py
- api.md
- frontend/coffee/create.coffee
- templates/create.html
#264 surfaced a bug which makes creating new mods broken now.
Until #264, we primarily filled the **game version** selector in `create.html` during (server-side) template rendering.
This step assigns `game_version.friendly_version` to the `value` attribute:
https://github.com/KSP-SpaceDock/SpaceDock/blob/e91894465c3a2885531355b9c813493ad93eaca4/templates/create.html#L72-L76
As soon as you switch the selected **game**, some JavaScript code is executed to refill the **game version** selector. However this JS code assigns `game_version.id` to the `value` attribute:
https://github.com/KSP-SpaceDock/SpaceDock/blob/e91894465c3a2885531355b9c813493ad93eaca4/templates/create.html#L179-L181
Since #264, the JS code is also executed once after page load, which results in the id being assigned all the …
> Fix creation of new mods

- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/profile.py
- KerbalStuff/common.py
- KerbalStuff/email.py
- emails/password-changed
- emails/password-reset
- frontend/coffee/profile.coffee
- templates/profile.html
SpaceDock is lacking a good way to change passwords. You can reset your password via `/forgot-password`, but we are not linking to it anywhere for one, and it's not something users would go to if they simply want to change it (and still now their old one).
There's a new API route `change_password` at `/api/user/<username>/change-password`. It requires the old password as well as the new password x2 as POST parameters.
It checks if the old password is correct, if the user for whom the password shall be changed is the one trying to do it, and whether the new passwords follow a few simple rules, now centrally defined in `accounts.check_password_criteria()` (it is also used by `register()` and `reset_password()`).
If it fulfills all the criteria, the new password is set in the database and we …
> Add password change option for users

- requirements-backend.txt
```
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/kombu/utils/objects.py", line 42, in __get__
return obj.__dict__[self.__name__]
KeyError: 'backend'
During handling of the above exception, another exception occurred:
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception …
```
> Add missing, undeclared future dependency of celery

- KerbalStuff/blueprints/api.py
- KerbalStuff/common.py
- KerbalStuff/custom_json.py
The API already uses a custom JSON encoder to format datetimes that are included in response dicts. Instead of taking advantage of this and adding timezone data in #265, we formatted one specific datetime to a string before the custom encoder has a chance to do its work. There are other datetimes in the API; some are formatted by the custom encoder, some have their own custom encoding code (which does the same thing). Ideally they should all use the same format, in a UTC time zone.
The API output puts spaces after commas and colons, which isn't necessary for machine-readable data, makes it look less professional, and wastes a tiny amount of network bandwidth.
- https://beta.spacedock.info/api/mod/2
GitHub by way of comparison doesn't use extra spaces in its API:
- …
> API: Set UTC TZ for all datetimes, prune whitespace

- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/email.py
- templates/admin-links.html
- templates/game.html
Mostly found while testing beta code. A bunch of smaller fixes and enhancements, see below:
1) Don't count unpublished mods on game page.
Closes #240 
2) Fix support channels missing from password-changed email
Forgot to add that parameter in #268. I also moved the transformation from a simple dict to a "map" list with `"name":` and `"channel_url":` in a separate function since we use it twice now.
3) Replace forum thread link on admin page with the current one.
It points to an old, no longer existing thread currently. I also shortened it so it fits on the right side too.
4) Allow admins to publish mods
I think this is handy to have especially with the locking feature from #260
5) Mark mod as recently updated if only the KSP compatibility changed.
Closes #171 
6) Remove unnecessary …
> Fix support channels missing from password-changed email, and others

- KerbalStuff/blueprints/mods.py
CKAN syncs up several fields from SpaceDock; name, homepage, source code, etc. Currently if the user makes a change, we have to wait for the NetKAN bot to schedule such mods for re-inflation. It would be nice to take care of it with a notification.
Now the `/mod/id/name/edit` route calls `notify_ckan` after saving changes to a CKAN-enabled mod (it already has a call to `send_to_ckan` for when the mod has _just_ been CKAN-enabled, and this other call is just for when it was already CKAN-enabled).
Also the CKAN notification fix from #270 is copied here as well, since it fits here and that PR is much larger. Whichever one merges first can keep it.
> - Unreachable code fixed; CKAN triggers weren't being sent after mod authors marked a mod compatible with the latest game version
> Notify CKAN after edits

- .github/workflows/pytest.yml
- KerbalStuff/app.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- tests/__init__.py
- tests/fixtures/client.py
- tests/fixtures/fake_config.py
- tests/test_api_errors.py
- tests/test_errors.py
The API currently returns the HTML error pages whenever we hit an 500 or 404.
This is not a good API design and already tripped us over with the mod upload previously, since we didn't account for non-JSON responses. We solved it by adding an extra check for the returned status code, but it would be nice if we always had a JSON where we could just check the `error` bool.
My first attempt was to create special error handlers only for the API routes, but Flask says no:
> However, the blueprint cannot handle 404 routing errors because the 404 occurs at the routing level before the blueprint can be determined.
https://flask.palletsprojects.com/en/1.1.x/errorhandling/#handling
(IMHO this restriction makes per-blueprint error handling practically useless, because 99.9% of errors you want to …
> Return JSON after errors in /api routes

- KerbalStuff/blueprints/api.py
- KerbalStuff/objects.py
- tests/test_api_mod.py
Some interest has been expressed in having download counts per mod version (see KSP-CKAN/NetKAN-Infra#109). The general idea is that some clients may wish to emphasize more recent downloads over older ones.
Now the API object returned for a ModVersion includes a `downloads` property that's the sum of the `DownloadEvent.downloads` rows associated with that version.
> Return ModVersion downloads in API

- KerbalStuff/blueprints/admin.py
- templates/admin-game-versions.html
- templates/admin-games.html
- templates/admin-publishers.html
- templates/admin.html
This pull request attempts to make the admin pages somewhat usable.
Problems | Changes
:-- | :--
The admin page's tabstrip contains Users, Blog, Publishers, Games, Game Versions, E-Mail, Links. The positioning of Blog is weird because it's in the middle of a bunch of record-editing tools, and far away from its fellow communication tool E-Mail. | Now the record editors are at the left and the communications tools are afterwards: Users, Publishers, Games, Game Versions, Blog, E-Mail, Links
If you search for a Publisher, Game, or Game Version and no matches are returned... ![image](https://user-images.githubusercontent.com/1559108/85492172-627a6180-b59a-11ea-8bf5-aafa265fa386.png) ... a pagination button is shown even though there's nothing to paginate, the section heading overlaps the …
> Admin page fixes

- KerbalStuff/search.py
- alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
- requirements-backend.txt
@DasSkelett is perturbed that a mod for KSP 1.1 is on the second page of the mod list by virtue of its high download count:
- https://spacedock.info/mod/79/BDArmory
This potentially could invite some users to download it, when it probably won't work if they try to use it with the current game, and they probably want something newer. The same problem applies across the board, once a mod accumulates a large number of downloads, nothing can knock it off the pedestal, whether it is maintained or abandoned.
Now the mod scoring system includes a new penalty for being horribly out of date. For a given mod, we look at the game version with which its default version is compatible, and for each newer known release of that game, we apply a 5% penalty. To avoid accumulating a big group of zero-score …
> Score penalties for incompatible mods

- KerbalStuff/celery.py
With #270 the behaviour of `celery.send_mail()` has been altered.
It requires `smtp-user` and `smtp-password` to be set in the `config.ini`, otherwise it returns without doing anything.
Before they were optional, and if present, used to log in into the mail server.
They shouldn't be necessary, sometimes mail server setup don't need explicit login to send a mail, this is also the case with SpaceDock alpha + beta + production. The mail server authenticates by whitelisted internal IP ranges.
Make both config options optional again.
Only if both are set we try to log in, otherwise we let the function continue without logging in.
This means that if the user is set but password isn't, we let the connection attempt fail hard so that it hopefully appears in the logs.
> Don't require smtp-user and -password to be set in send_mail()

- KerbalStuff/app.py
- KerbalStuff/blueprints/api.py
- spacedock
```
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/common.py", line 81, in go
ret = f(*args, **kwargs)
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/common.py", line 124, in wrapper
result = f(*args, **kwargs)
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/blueprints/api.py", line 152, in wrapper
return func(*args, **kwargs)
File …
```
> Run db.commit() before calculating mod.score in update_mod()

- KerbalStuff/search.py
- alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
```
(SpaceDock) root@sd1a:/var/www/virtual/spacedock.info/htdocs/SpaceDock# python3 spacedock database migrate
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 77f76102f99c -> 7993492be4eb, Add locked, lock_reason, locked_by and locked_by_id to mod
INFO  [alembic.runtime.migration] Running upgrade 7993492be4eb -> d6f41a805840, Index columns passed to .order_by()
INFO  [alembic.runtime.migration] Running upgrade d6f41a805840 -> 85be165bc5dc, Add Mod.score
File "spacedock", line 216, in <module>
cli()
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return …
```
> Zero score for mods without default versions

- KerbalStuff/search.py
`/kerbal-space-program/browse/top` only returns Scatterer in @V1TA5's test instance, and you can jump to subsequent pages to get 1, 2, or 3 other mods where there should be 30 per page.
The query in `search_mods` is returning many many duplicates, because `.join(Mod.versions)` makes it return one entry per ModVersion. Scatterer has lots of releases, so it takes up a whole page, and so on for other mods with long histories.
Now we don't join to Mod.versions anymore. Each entry will represent one mod. This will properly populate the search results.
> Don't join mod_search to ModVersions

- KerbalStuff/blueprints/api.py
- tests/test_api_mod.py
After the production upgrade the API has gotten really slow wherever it returns mod info.
Additionally we experience the whole site slowing down over time. VITAS reported the db being the cause of the slowdown.
I suspect it is a result of #286.
Remove the `"downloads": version.download_count()` line again, hoping it mitigates the problem for now and gives us time to re-implement it less db-hungry.
> Remove download count from mod version api again

- KerbalStuff/blueprints/mods.py
- templates/mod.html
- templates/mod_list.html
Currently SpaceDock supports these formats to download a mod:
1. https://spacedock.info/mod/id/modname/download/version
2. https://spacedock.info/mod/id/download/version
Both require you to know the version you want; it would be nice to generate a permalink that always returns the default version without having to know what it is.
Now a new URL format returns the default download for a given mod, based on format 1 above with the version omitted (these are not currently valid links and are provided just as examples):
- http://spacedock.info/mod/id/modname/download
The mod name can also be omitted:
- https://spacedock.info/mod/id/download
If you name your mod `download`, it will be impossible to view the mod info page via the `/mod/id/name` route. But it will already be impossible to do all …
> URL for current latest download

- KerbalStuff/celery.py
- KerbalStuff/ckan.py
- config.ini.example
The CKAN team maintains a JSON file with all the known versions of KSP:
- https://github.com/KSP-CKAN/CKAN-meta/raw/master/builds.json
This is generally updated rapidly after a new version of KSP comes out.
Currently SpaceDock needs to be updated separately. I previously suggested automatically syncing them up, and @V1TA5 sounded amenable.
Now if you set the config parameter `ksp-game-id` to the ID of your KSP Game, you too can enjoy beautiful automatic version syncing:
A scheduled task runs once an hour that parses CKAN's builds.json file and adds new GameVersions as needed.
> Auto-import KSP versions from CKAN

- KerbalStuff/blueprints/api.py
In #282 we added CKAN notifications for "Edit Mod" and auto-update (set latest release compatible with latest game version).
Now we also notify for:
- Updating a mod's background (which CKAN stores in `CkanModule.resources.x_screenshot`)
- Adding and removing a co-author (which CKAN stores in `CkanModule.author`)
- Changing the default version (which determines which version CKAN inflates)
This will allow CKAN to update its metadata promptly.
> Notify CKAN after more events

- KerbalStuff/blueprints/mods.py
- templates/edit_mod.html
I think some users don't realize that mods on SpaceDock have to be "published" to be visible. For example, see KSP-CKAN/NetKAN#7995, which requests CKAN indexing for a mod that as of this writing is not published after 3 days.
Now the mod editing page has a new "Save & Publish" button when editing a mod that isn't published, which saves the changes and sets the mod as published. Hopefully people will at least see this button and think about what publishing might mean, and they might even click it!
> Add Save & Publish button to edit mod page if not published

- KerbalStuff/app.py
- KerbalStuff/blueprints/blog.py
- KerbalStuff/common.py
- KerbalStuff/objects.py
- alembic/versions/2020_06_29_11_37_00-544564b4e738.py
- frontend/styles/stylesheet.scss
- templates/admin-blog.html
- templates/blog.html
- templates/blog_index.html
- templates/edit_blog.html
- templates/layout.html
When SpaceDock has a planned downtime, it's a struggle to notify users ahead of time. The only place that all SpaceDock users go is SpaceDock itself (unless you count CKAN users who don't even do that), but currently it has no ability to display such notifications.
Now a new "Global announcement at top of all pages" checkbox appears when creating or editing a blog post. If checked, a new `BlogPost.announcement` column is set to true. All blog posts with that column set to true are pulled in to (Markdown-enabled) banners across the top of every page. To make sure this is fast, the new column is indexed.
To remove an announcement, the admin can edit the blog post and uncheck the checkbox.
This pull request also attempts to make the blog somewhat usable.
Problems | Changes
:-- | :--
The blog …
> Announcements and blog fixes

- KerbalStuff/blueprints/admin.py
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/objects.py
- KerbalStuff/search.py
- alembic/versions/2020_06_26_01_24-1aa078e0fb7e.py
- frontend/coffee/edit_pack.coffee
- frontend/coffee/global.coffee
- frontend/coffee/list.coffee
- frontend/static/css/bootstrap-theme.css
- frontend/styles/listing.scss
- frontend/styles/stylesheet.scss
- templates/admin-users.html
- templates/create_list.html
- templates/edit_list.html
- templates/game.html
- templates/index.html
- templates/layout.html
- templates/mod-box.html
- templates/mod.html
- templates/mod_list.html
- templates/pack-box.html
- templates/packs.html
- templates/view_profile.html
- tests/test_api_mod.py
This pull request attempts to make mod packs somewhat usable, plus a few convenience/usability fixes.
Problems | Changes
:-- | :--
If you click Login to log in, you have to click the Username field to start typing. | Now the Username field has focus by default.
A mod box shows the game version, but not the game. | Now the default version, game, and game version are shown, which fixes #172.
If you have no forum name, twitter name, reddit name, irc name, or description, your user profile will have a blank box at the top. | Now the blank box is not shown.
The admin page doesn't say which users are admins | Now an Admin column shows who's an admin
The user profile doesn't say whether the user is an admin or allow an admin to make them an admin | Now admin-visible section of the user profile …
> Modpack fixes

- KerbalStuff/blueprints/mods.py
- config.ini.example
- requirements-backend.txt
See #312, when a mod author deletes a release, it continues to be served at the same URL for some time.
The Apache Traffic Server caches downloads, and it doesn't know when they've been deleted.
Now we issue a `PURGE` request to the host set in the `cdn-internal` setting in `config.ini` when we delete a mod version, to tell ATS to remove that URL from its cache:
- https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/storage/index.en.html#removing-an-object-from-the-cache
This is not a standard HTTP verb, so we have to use the syntax for custom verbs:
- https://requests.readthedocs.io/en/master/user/advanced/#http-verbs
Fixes #312.
> Purge ATS cache upon deletion

- Dockerfile
- KerbalStuff/blueprints/api.py
- README.md
- frontend/Dockerfile
- templates/pack-box.html
Some smaller fixes and updates:
* Render markdown-formatted modpack descriptions (spotted by @HebaruSan)
* Log exceptions to syslog when mod zips can't be saved
* Update README.md for the server setup steps according to what I had to do for re-setup alpha + beta
* Update backend Docker image to Python3.8 which we are also using in prod + alpha + beta
* Update frontend Docker image to nginx:latest since 1.17 is a bit old by now, and I think it does no harm to automatically stay up-to-date in development setups.
> Render markdown-formatted modpack descriptions; other fixes and updates

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/objects.py
- alembic/versions/2020_07_20_19_00_00-73c9d707134b.py
- frontend/coffee/stats.coffee
- frontend/coffee/statworker.coffee
- templates/mod.html
The mod info page currently shows how many downloads each release had on each of the past 30 days, but there is no total count per version. It would be informative to see how a mod's releases have trended over time.
Now the mod info page's stats tab shows a bar chart of how many downloads each version has had:
The counting is done via sqlalchemy magic to minimize data loaded from the db.
Fixes #185.
`/random` is slower than it needs to be because it loads all of the published mods to the client to pick one. Now we just get the count, choose a random index, and ask the db to hand us just that one mod. Should be faster.
> Chart downloads per mod version

- KerbalStuff/blueprints/api.py
While I was messing around with remaking OpenDock to use the newest version of Vue (and correctly use it), I noticed that `/api/games` didn't return the `gameshort` for the games.
> Add gameshort to returned object in /api/games

- KerbalStuff/blueprints/api.py
- KerbalStuff/objects.py
- KerbalStuff/thumbnail.py
- config.ini.example
1) Thumbnail images are generated as JPEG but saved under whichever file extension the source background image has. So there are thumbnails with `.png` which are actually JPEGs.
2) Thumbnail creation for background images with alpha channel fails:
```
OSError: cannot write mode RGBA as JPEG 
```
3) When the thumbnail creation fails, we also delete the source background. This leads to strange behaviours combined with the caching traffic server, where images seem to magically remove themselves after a varying timespan.
4) VITAS wants the quality of thumbnails to be configurable.
5) Uploads of background images with the extension `.jpeg` are not allowed, only `.jpg` and `.png`.
1) Thumbnails are now explicitly saved with `.jpg`
2) If the source image has a alpha channel we convert the …
> Thumbnail image creation fixes

- KerbalStuff/blueprints/mods.py
- config.ini.example
Chrome shows an "unsecure download" warning since the latest version for mod downloads from SpaceDock, and you have to explicitly allow each download:
This is because we redirect via HTTP for downloads on setups where `cdn-domain` is set:
With the next update released in 2 days, Chrome will entirely **block** our mod downloads:
https://blog.chromium.org/2020/02/protecting-users-from-insecure.html
Now we use the `protocol` setting from the `config.ini` to decide which scheme to use if a "CDN" is used.
This implicitly forces deployments of this code to also use HTTPS for their CDN if they use HTTPS on the main domain. This isn't really a drawback IMHO, it only makes sense, and otherwise they'd be hit by the exact same problem anyways.
This probably can't be tested locally, but we should be …
> Get scheme from 'protocol' config for mod download redirection to CDN

- systemd/spacedock-celery.service
After the server restart last Friday, celery got auto-upgraded to version 5.0.0, since which the value of the `--loglevel` commandline argument has to be uppercase:
```
Oct  3 00:00:51 sd-alpha celery[4482]: Usage: celery worker [OPTIONS]
Oct  3 00:00:51 sd-alpha celery[4482]: Try 'celery worker --help' for help.
Oct  3 00:00:51 sd-alpha celery[4482]: Error: Invalid value for '-l' / '--loglevel': invalid choice: info. (choose from DEBUG, INFO, WARNING, ERROR, CRITICAL, FATAL)
```
This resulted in all SpaceDock services that are part of `spacedock.target` being restarted by systemd every minute or so.
Changed `--loglevel=info` to `--loglevel=INFO` in `systemd/spacedock-celery.py`.
This is already changed on production to get it working again, and alpha+beta which I used to test if it …
> Fix celery loglevel argument

- KerbalStuff/blueprints/mods.py
- frontend/static/css/bootstrap-theme.css
- frontend/styles/mod.scss
- frontend/styles/timeline.scss
- templates/edit_mod.html
- templates/mod.html
#293 tried to fix some parts of utterly broken `bootstrap.css` on the run, which apparently broke the icons,
because the now uncommented lines overwrite the ones from `timeline.scss`, setting the icon color to the background color.
Thanks @V1TA5 for discovering the exact cause.
Since #293 you conveniently get redirected to the mod edit page after creating a mod. However, we lost the banner saying you should edit the description and stuff, which is only displayed on the mod page which is now skipped.
The `stupid_user` check...
https://github.com/KSP-SpaceDock/SpaceDock/blob/b3220388dd71e5333710bde557683c3fd306b993/KerbalStuff/blueprints/mods.py#L440-L441
...that checks whether a user has edited the default description before publishing, doesn't work anymore. Apparently it's caused by the …
> Fix timeline CSS and default description check

- frontend/static/css/bootstrap-theme.css
- frontend/styles/index.scss
Another legacy KerbalStuff hack of bootstrap exposed by #293 trying to remove syntax errors.
Now `div.service-icon` is removed from bootstrap and reconciled with the existing properties of `.service-icon` in index.scss.
> Fix service icons on logged out index

- KerbalStuff/blueprints/profile.py
- templates/view_profile.html
5 or so years ago, the KSP forum changed software and the old way of tracking a user's forum profile broke. Before that time, it was possible to use a server API to translate a forum username into an ID, which could then in turn generate a link to the profile on the fly. With this option gone, the devs back then apparently changed it to a plain text field, added some `TODO`s to the code, and gave up.
Since then, the de facto standard established by users is to paste your whole profile URL into the field. I surveyed the most recent 250 pages of users created, and these users have full URLs in the profile field:
- https://spacedock.info/profile/L0ck0n
- https://spacedock.info/profile/tetraflon
- https://spacedock.info/profile/aazard
- https://spacedock.info/profile/BuzzFeed4Lief
- …
> Profile forum URLs as links

- frontend/coffee/mods.coffee
It's often useful to refer to a mod's change log (list of historical versions) when investigating some issue, but sometimes users don't know where it is.
Now these links will open the corresponding tabs:
- https://alpha.spacedock.info/mod/1#info
- https://alpha.spacedock.info/mod/1#changelog
- https://alpha.spacedock.info/mod/1#stats
Is there a better access point for toggling these other than removing and adding the `active` CSS class? I could not find out much about how the tab control is supposed to work.
Fixes #315.
> Open mod tabs from URL

- KerbalStuff/blueprints/api.py
The API includes pending authors:
https://spacedock.info/mod/2062/KSC%20Extended
https://spacedock.info/api/mod/2062
This effectively reports changes to author teams before they're confirmed by the participants.
Found after https://github.com/KSP-CKAN/CKAN-meta/commit/5b17390e48094a9a7b4330cb5e0b9cb3d26cad26
The `Mod.shared_authors` objects have an `accepted` property that is set to `True` when a pending author is confirmed. The UI checks it, but the API doesn't.
Now only confirmed authors are returned.
> Exclude pending authors from API

- KerbalStuff/app.py
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/objects.py
- templates/game.html
- templates/mod-box.html
- templates/mod.html
- templates/pack-box.html
- There are a lot of empty modpacks cluttering [the list on prod](https://spacedock.info/packs)
- Long modpack descriptions are displayed in full, stretching the box crazily
- Long game names are displayed in full in mod listings, which takes up a lot of space:
- If you invite a co-author to a mod that already has some, the authors list shows an extra comma in the time before the new author accepts:
- The per-game mod listings were needlessly different depending on whether you were logged in or logged out
- Mods with only one release are intended to be excluded from Recently Updated, but they're included
- It was previously more difficult to figure out how to add a mod to a pack, so there's just an accumulation of bad data
- We have a max-height and overflow set up, but on a `p` element, …
> Minor UI tweaks

- KerbalStuff/app.py
- KerbalStuff/common.py
- frontend/coffee/global.coffee
- requirements-backend.txt
- templates/mod.html
- templates/mod_list.html
- templates/pack-box.html
- templates/rss-mod.xml
- templates/view_profile.html
Recently I spotted some warning messages in the browser console regarding our cookie usage:
Especially alerting was the message that the session cookie would be rejected in the future, which would likely break our login functionality.
See https://github.com/KSP-SpaceDock/SpaceDock/pull/335#pullrequestreview-574871740
Users can fill in arbitrary HTML code into mod / mod pack / profile descriptions, which won't be escaped but embedded and executed as is when someones views the page.
You can't mark code blocks using triple backticks like on GitHub.
Browsers are moving to reject cookies that have neither `SameSite` nor `Secure` set, because those are vulnerable to XSS and CSRF attacks.
For details, see
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#Secure
* …
> Set 'Secure', 'HttpOnly' and 'SameSite' attributes on cookies; escape untrusted HTML from user input

- KerbalStuff/app.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/ckan.py
- docker-compose-prod.yml
- docker-compose.yml
- templates/edit_mod.html
* CKAN doesn't get pull requests for around half of new mods with the CKAN badge enabled.
The following steps lead to no notification sent:
1) Create mod
2) Edit mod, check CKAN badge, "Save Changes"
3) Edit mod, "Edit & Publish"
* The "Add to CKAN" checkbox is hidden after it has been enabled once. Authors thus can't verify whether they checked it and might get confused; they also can't disable it again for unpublished mods, even though it wouldn't create any problems there.
* Once the checkbox is activated, it's set in stone. However sometimes it happens that CKAN doesn't index a mod it gets a PR for for whatever reason. It would be nice if admins could deactivate the checkbox again.
* For some reason the tooltip for the CKAN checkbox doesn't work anymore.
* The "(un)locked" and "edit" …
> Several CKAN integration fixes

- KerbalStuff/blueprints/mods.py
- templates/mod.html
This is similar to what @HebaruSan did in #331, except for source code repositories and on the mod page.
The source code link is basically the last link in the mod info box that is displayed as is.
All other links are shortened if possible, both to make them prettier and to hide unnecessary detail, and to save some horizontal space, useful on mobile devices (although there's more that's broken currently).
Now we try to get a short link text if it points to a GitHub or GitLab repository.
It's formatted like you usually shorten the names of repositories: `<Username>/<Repository>`
For example: `KSP-SpaceDock/SpaceDock` or `KSP-CKAN/CKAN` or `godarklight/DarkMultiPlayer`
It's matched using a regex. If it doesn't match (e.g. not hosted on GitHub/GitLab), we display the link as is. I thought …
> Abbreviate link for mod source code repository

- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/objects.py
- requirements-backend.txt
- tests/__init__.py
- tests/test_objects_user.py
Checking passwords (and setting passwords) is something that must be rock-solid.
For this it makes sense to keep as much logic of it at a single place, so you don't have to rewrite it half a dozen times with the risk of introducing a nasty bug each time.
Also bcrypt 3.1.0 introduced a new `bcrypt.checkpw(<input to check>, <hashed password>)` function that is way more intuitive than the old `bcrypt.hashpw(<input>, <hashed password>) == <hashed password>`.
If you are wondering how the old one works, `bcrypt.hashpw()` reads the salt from the hashed password (bcrypt hashes save the salt in front of the actual pw hash) and hashes the clear text input using this salt. Then we compare the output with the actual hash.
The new method basically still does the same in the background, but we don't …
> Centralize password check as method of 'User' objects

- frontend/coffee/update.coffee
- templates/update.html
It happens quite regularly that mod authors get confused about their own versioning system.
They start with a version numbers that all have a `v`  prefix, but one day they decide to omit it (or more precisely: they forget about it). Of course it happens the other way around just as often, or sometimes even mixing lowercase `v`s with uppercase `v`s, or all sorts of variations thereof.
In theory you are supposed to decide for one format at the beginning, and then stick to it for the lifetime of your software.
Btw., did you know that [semver.org](https://semver.org/) suggests that only version numbers without `v` (or `V`) prefix [are considered semantic](https://semver.org/#is-v123-a-semantic-version)?
This trips up every system that tries to sort mod versions by their version number, for …
> Warn authors when changing version prefixes

- KerbalStuff/app.py
- KerbalStuff/blueprints/admin.py
- KerbalStuff/middleware/profiler.py
- KerbalStuff/profiling.py
- config.ini.example
- requirements-backend.txt
- templates/admin-profiling-viz.html
- templates/admin-profiling.html
- templates/admin.html
The production server has performance slowdowns when it's the evening in the US. We want to capture profiling information to figure out why this happens.
Now there are two new configuration parameters:
https://github.com/KSP-SpaceDock/SpaceDock/blob/50a089024ba52f768f5a18ba59f6824874d580f6/config.ini.example#L104-L107
If you set `profile-dir` before starting the server (or set it and restart), then it will begin outputting profiling data to the given folder. The second parameter can be used to control how often profiling happens; to profile 1 out of 100 requests, set it to 100; to profile 1 out of 1000 requests, set it to 1000. By default all requests would be profiled, so you should probably set this setting. Admin pages are never profiled.
The captured profiling data can be viewed in …
> Profiling with admin visualization for the backend

- KerbalStuff/blueprints/admin.py
- KerbalStuff/middleware/profiler.py
- templates/admin-page-nav.html
- When #346 first deployed on `alpha`, only unprofiled pages would load. The rest were non-functional, and there was almost no logging or debugging output that we could find to explain why.
- If you perform a search in the admin pages, it might be multiple pages, but clicking to go to another page will discard the search. This makes it very hard to browse long searches.
I made the profile dir manually, and I forgot to chown/chmod it so the `www-data` user could write to it. This made the profiler's base class throw on this line:
https://github.com/pallets/werkzeug/blob/248a79cf9292a4a5e1deec4906a1f5296f151172/src/werkzeug/middleware/profiler.py#L128
The right thing to do was **not** make the dir, because the code will make it if needed, with the right permissions.
This should be a rare …
> Fall back to unprofiled if profile dir is unwritable

- KerbalStuff/app.py
- KerbalStuff/blueprints/admin.py
- templates/admin-game-versions.html
- templates/admin-games.html
- templates/admin-page-nav.html
- templates/admin-publishers.html
- templates/admin-users.html
The admin pages are very cluttered.
- Games, game versions, and publishers that aren't active (thousands of them)
- User accounts that aren't public (thousands and thousands of them)
This makes it difficult to find the useful data in each list much of the time.
(Noticed while looking into the possibility of adding profiling visualizations here.)
Now each admin listing has a new checkbox, unchecked by default, see below for their labels. If unchecked, the non-public or inactive records for that listing are filtered out. The user can check the checkbox to view all rows, as previously.
SpaceDock spends 90% of each request compiling templates unnecessarily because of this line:
https://github.com/KSP-SpaceDock/SpaceDock/blob/645ab906d3c0025322accfb46b9ccfdd7c90a7b8/KerbalStuff/app.py#L54
See …
> Filter junk out of admin pages and make site 10x faster

- KerbalStuff/app.py
- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/common.py
- KerbalStuff/search.py
- requirements-backend.txt
Thanks to #346 we now have very valuable profiling data for our backend. After fixing the previous bottleneck, repeated template bytecode compilation due to disabled caching, the major part of most requests is now spent on database queries.
The answer: moar caching!
This PR does an initial step at caching the most common database queries (some of them executed on every request), that tend to not change at all or only very infrequently, or don't hurt if they are a bit out of date.
It's the low hanging fruit, there's still a lot more we should eventually cache, but those need some refactoring and other bigger changes, or careful planning. I preferred to get the easy stuff in first.
We are caching all of the following requests in a `TTLCache`, that is s LRU cache with timeouts, using the …
> Cache results of common database queries

- templates/mod_list.html
If a user creates a modpack without a description, SpaceDock displays this message:
It's wrong in two ways:
1. The user is addressed as if they own the mod pack even if they aren't the creator and could not edit it
2. It suggests that there are no mods added, even if there are several added
Just sloppiness in the `mod_list.html` template.
- Now if you can't edit, the message just says "No description."
- Now if you can edit and there are mods, the message just mentions the description being missing
- Otherwise the current message is shown
> Better messaging for descriptionless modpacks

- KerbalStuff/app.py
- KerbalStuff/common.py
- KerbalStuff/search.py
- requirements-backend.txt
A partial revert of #349, see https://github.com/KSP-SpaceDock/SpaceDock/pull/349#issuecomment-836572854
SqlAlchemy doesn't like its returned objects to be cached, due to its lazy loading behaviour.
Eager loading isn't an option for `Mod` objects, since they have a ton of relationships that kill the database when queried at once.
Maybe there's a solution for this somewhere, but I haven't found one yet. Let's revert the caching, to make the site stable again.
> Revert caching of database queries

- .gitignore
- KerbalStuff/middleware/profiler.py
- docker-compose.yml
- prepare.sh
- requirements-backend.txt
- requirements-celery.txt
- requirements-prod.txt
Right now, every restart of the production instance (or alpha/beta as well) upgrades all Python dependencies to their very latest version, if unpinned (and most of them are).
On alpha, this lead to the backend not coming back up again recently, because it silently upgraded to Flask 2.0, but stayed at Werkzeug 0.16.1 because it is pinned, while Flask 2.0 needs Werkzeug >=2.0 to work.
This could be mitigated by upgrading the installed pip (20.0.2) to the latest version, since [pip 20.3 gained a new, fixed dependency resolver](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020), which now installs the latest Flask that still works with Werkzeug 0.16.1 (1.1.4).
If we didn't have Werkzeug pinned, alpha would've been broken as well:
```
Traceback (most …
```
> Freeze dependencies on version they have at deployment

- .github/workflows/mypy.yml
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/common.py
- KerbalStuff/objects.py
- alembic/versions/2021_06_09_19_00_00-c0e44e063159.py
- alembic/versions/alembic.pyi
- requirements-tests.txt
Flame graph profiling from #346 has revealed that accessing `DownloadEvent` is a substantial part of loading a mod page and especially starting a download:
`DownloadEvent` is a big table with a lot of rows, and we filter it by columns that aren't indexed (`mod_id` and `version_id`). This means the database engine has to search every row and check whether they match.
- New multi-column index in `DownloadEvent`: `(mod_id, created)`, to be used for loading the mod page
- New multi-column index in `DownloadEvent`: `(version_id, created)`, to be used when starting downloads
- The download route now only filters by `DownloadEvent.version_id` since if this matches then `DownloadEvent.mod_id` will match as well, and both will now be indexed
- The download route previously retrieved …
> Speed up DownloadEvent queries

- KerbalStuff/objects.py
- alembic/versions/2021_06_09_19_00_00-c0e44e063159.py
After #370, this mod gives a 500 status:
- https://alpha.spacedock.info/mod/3/Test%20download%20path
Server says:
`sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range
[SQL: UPDATE modversion SET download_size=%(download_size)s WHERE modversion.id = %(modversion_id)s]
[parameters: {'download_size': 2147831870, 'modversion_id': 29}]`
The type of `ModVersion.download_size` is `sqlalchemy.Integer` (SQL's INT), which can only support downloads up to 2 GiB. That file and some mods are bigger.
Now we use `BigInteger` (BIGINT) instead.
Note that the migration is changed in-place, so it will have to be downgraded manually on alpha. I'm told this has been done already.
> Make download_size a BigInteger

- KerbalStuff/blueprints/anonymous.py
The `/download/` route handler tries to redirect mod downloads to the CDN here (`_cfg("cdn-domain")` is `https://spacedock.info/content/`):
https://github.com/KSP-SpaceDock/SpaceDock/blob/ae68684fbca36be5992e39bacf4323f88b746a60/KerbalStuff/blueprints/mods.py#L549-L552
The idea is that the `https://spacedock.info/content/` URLs should be handled by a fast server with access to the storage, what we've been calling AW (Apache Web Server).
CDN handling of downloads is disabled in the server config for reasons that nobody remembers (and turning it on temporarily produced unexplained timeouts and 502 statuses):
So the `/content/` request comes back to the backend here:
https://github.com/KSP-SpaceDock/SpaceDock/blob/ae68684fbca36be5992e39bacf4323f88b746a60/KerbalStuff/blueprints/anonymous.py#L4 …
> Serve /content/ routes with X-Sendfile

- KerbalStuff/app.py
- KerbalStuff/blueprints/blog.py
- KerbalStuff/objects.py
- alembic/versions/2021_06_23_12_00_00-426e0b848d77.py
- alembic/versions/alembic.pyi
- templates/admin-blog.html
- templates/edit_blog.html
Today we put this in production to help decide whether to move forward with #348:
I thought using an announcement for this was so clever, but it's going to pull in users without accounts who have no idea that SpaceDock has "follow" functionality or email notifications already. That will add some noise to the discussion; it would be better if we could target logged in users only.
Now a new "Only show this to logged in users" checkbox is available when creating or editing a blog post, which saves to a new Boolean column. If this column is True, then you have to be logged in to see that row, whether you're looking at the blog index or as an announcement. This way things that pertain only to logged in users can be flagged as such.
> Checkbox to hide a blog post or announcement from anonymous users

- KerbalStuff/search.py
Mod scores are the default sort when browsing mods and are meant to reflect the overall quality or popularity of a mod. Since that's a broad concept, the scores pull from many different fields, primarily downloads, but also follower counts, how filled-in the mod's data is, how old and up to date the mod is, etc.
If a user puts another user's mod in a mod pack, this is implicitly an endorsement of that mod, but currently we don't take advantage of this knowledge.
Now each time another user adds a mod to a mod pack, the equivalent of 15 downloads is added to that mod's score.
For comparison, following a mod contributes the equivalent of 10 downloads. I felt that clicking the Follow button or a star icon is a much easier action than creating a mod pack, typing a name, clicking Add, then …
> Boost scores for mods in other users' mod packs

- KerbalStuff/blueprints/lists.py
The mod packs listing looks a bit better now, but you have to scroll down to get to the next/previous page buttons.
- https://spacedock.info/packs/kerbal-space-program
Also this morning we found that 3 of the 4 Balsa mod packs on production were advertisements from those user accounts about having someone do your homework or free laptops or finding European women to date.
Mods are shown in pages of 5 rows each.
Mod packs are likewise shown in pages of 5 rows each, even though they are twice as tall.
Mod packs were shown in the listing if they had zero mods and a description. This was intended to allow users to list mods that aren't on SpaceDock in the description, but that turned out to enable abuse.
Now we show 9 mod packs per page instead of 15. This will be 3 rows, and fit the …
> Fewer modpacks per page, hide modpacks without mods

- KerbalStuff/blueprints/profile.py
- templates/view_profile.html
In #331, we added automatic parsing of forum links on the profile page to make them more easily clickable.
However, thanks to #345, we are able to easily jump back to the very earliest accounts, which predate the ubiquity of HTTPS on the interwebs, so their forum links start with `http://`:
- https://spacedock.info/profile/SpaceIsBig42
- https://spacedock.info/profile/Snark
- https://spacedock.info/profile/daniel_l
- https://spacedock.info/profile/erendrake
- https://spacedock.info/profile/simon56modder
One user even left off that part of the URL completely:
- https://spacedock.info/profile/theJesuit
Currently these profiles do not benefit from the parsing and formatting of #331.
The regex for parsing the links starts with `https`. This is unnecessarily restrictive.
Now the regex allows …
> Allow http or nothing in forum links

- KerbalStuff/blueprints/profile.py
- KerbalStuff/email.py
- KerbalStuff/objects.py
- alembic/versions/2021_06_28_19_00_00-17fbd4ff8193.py
- alembic/versions/alembic.pyi
- frontend/coffee/profile.coffee
- frontend/styles/mod.scss
- templates/profile.html
Currently if you follow a mod, you receive all email notifications for it. Some users might not want to receive notifications for compatibility updates.
Fixes #333 (the part about ignoring the auto-update email).
Now if you edit your profile, a new section lists the mods you follow, with two checkboxes for each. The rows are striped to make it easier to pick out the associations between the contents of each row:
If you uncheck a checkbox (and save your changes), you won't receive that notification for that mod anymore. Each column of checkboxes has "Check all" and "Uncheck all" buttons that check and uncheck all the checkboxes in that column, so users can easily disable all notifications of a particular type.
Admins are allowed to edit these settings for other users in case someone …
> Let users choose which emails to receive

- KerbalStuff/blueprints/api.py
- frontend/coffee/create.coffee
- frontend/styles/create.scss
- templates/create.html
Some mods have very long short decriptions, including such things as previous maintainers and dependencies. Looking at it from a user experience point of view, we suspect this is because the short description field is the only description field on the mod creation page, so the user may not know that a long description field exists and will be available later.
Now the long description field is added to the mod creation page. In addition, the short description now has a placeholder:
Together, these will hopefully encourage users to enter the long detailed info in the long description instead of the short description.
I tried to add a placeholder for the long description, but I was not able to get that to work. I think the CodeMirror editor requires an add-on to do it, but we're using an old …
> Add long description to mod creation page

- KerbalStuff/app.py
- KerbalStuff/middleware/session_interface.py
We were brainstorming ways to use @V1TA5's Apache Traffic Server to speed things up, and one idea that came up was to cache anonymous requests. If you are logged in, then several parts of each page depend dynamically on your user context. But if you're **not** logged in, then you and every other anonymous user will see pretty much the same thing for every page. Currently those requests go all the way to the backend, hit the database, render a Jinja2 template, etc., just to regenerate the same page that everyone else sees who is not logged in.
Currently there's no way for anyone other than the backend to tell the difference between a logged in and logged out user. They all have a `session` cookie that contains some little bits of data, probably from here, maybe also some places in Flask …
> Eliminate anonymous session cookies

- .github/workflows/mypy.yml
- .github/workflows/pytest.yml
- KerbalStuff/app.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/ckan.py
- KerbalStuff/common.py
- KerbalStuff/config.py
- KerbalStuff/email.py
- KerbalStuff/stubs/jinja2.pyi
- requirements-backend.txt
- templates/layout.html
- templates/mod.html
If a logged in admin user tries to open https://spacedock.info/mod/1967 , a 500 error occurs:
We found this in the server log:
```
2021-07-23 15:22:54,835 ERROR Backend:496 Exception on /mod/1967 [GET]
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/common.py", line 64, in go
ret = f(*args, **kwargs)
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/blueprints/mods.py", line …
```
> Handle missing default mod version, don't close db before rendering templates

- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/mods.py
- templates/edit_list.html
- templates/edit_mod.html
- templates/mod_list.html
After a mod is created, its name is locked in permanently and can't be edited. If the author notices an error in the name and wants to fix it, they can't. This leads some authors to delete a mod and create a "new" mod to replace it, which is not great since all the releases up to that point are deleted and must be re-uploaded if they are to be available under the new entry.
Modpack names also can't be edited.
This is a strange and very unforgiving way for a web site to work, demanding perfection on the first edit. It may originally have been done this way because of how uploaded files were named at some point, but now the storage path is saved to the `ModVersion` row and can be found regardless of the current name.
Non-exhaustive list of known cases where a mod is stuck with a name that …
> Allow editing names of mods and modpacks

- KerbalStuff/celery.py
- KerbalStuff/objects.py
- alembic/versions/2021_06_28_19_00_00-17fbd4ff8193.py
After #369 was merged, the alpha server was left in a semi-functional state because its alembic migration wasn't executed. This command fixed it (I used the migration id in place of `head`, but I want to document the best version of it):
```
cd /SpaceDock
bin/alembic upgrade head
```
This happens automatically when you run `./start-server.sh`, via `./spacedock database migrate`:
https://github.com/KSP-SpaceDock/SpaceDock/blob/ebb54cb85da0ea798cdbc3578e52b56fd04ee0c2/start-server.sh#L34
... which does this:
https://github.com/KSP-SpaceDock/SpaceDock/blob/ebb54cb85da0ea798cdbc3578e52b56fd04ee0c2/spacedock#L12-L15
https://github.com/KSP-SpaceDock/SpaceDock/blob/ebb54cb85da0ea798cdbc3578e52b56fd04ee0c2/spacedock#L75-L79
Now after the web hook pulls changes from GitHub, and before it restarts …
> Run database migrations after pulling changes

- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/blueprints/profile.py
- KerbalStuff/common.py
- KerbalStuff/email.py
- KerbalStuff/objects.py
- KerbalStuff/thumbnail.py
- alembic/versions/2021_07_29_18_00_833ba1ee8c72.py
- docker-compose.yml
- frontend/coffee/edit_mod.coffee
- frontend/coffee/profile.coffee
- frontend/configs/nginx.nginx
- spacedock
- templates/create.html
- templates/edit_mod.html
- templates/layout.html
- templates/mod-box.html
- templates/mod.html
- templates/profile.html
- templates/view_profile.html
Sorry, this ended up way bigger than I hoped, due to the background image URL issue.
Our content path handling is currently all over the place. Every function that saves or accesses some user content from disk has its own implementation to find the location.
Profile background images are not saved in the user folder, but instead we create a new folder per upload, with the timestamp in the folder name. When a profile background is deleted, the folder stays behind, empty:
```
├── HebaruSan-1622467520.5473514_1
├── HebaruSan-1622467781.61281_1
├── HebaruSan-1622467793.0606115_1
│   └── HebaruSan.jpg
├── HebaruSan_1
│   └── CKAN_Publish_Test
│       └── CKAN_Publish_Test-12345.zip
```
---
The background image URL handling is pretty awful right now:
When uploading background images (mods and …
> Unify storage base path and fix background image URLs

- KerbalStuff/common.py
- KerbalStuff/kerbdown.py
- templates/markdown.html
https://spacedock.info/markdown says:
> You can also embed YouTube videos and Imgur albums by wrapping the URL in brackets (specific to SpaceDock):
> 
> `[[https://www.youtube.com/watch?v=T4rfHAqs9EI]]`
However, if you try to use this currently, it just renders as an escaped inline `<iframe>`:
https://spacedock.info/mod/141/scatterer
#336 added a Bleach sanitization pass to our Markdown rendering, which only allows certain tags and attributes to be included in the rendered HTML. Currently `iframe` is not on the allowed list, and the above embedding functionality works by generating an `iframe` element.
Now `iframe` is allowed, but we apply extra validation to it. Only the attributes generated by SD's embed code are allowed, and for `src` specifically, only values beginning with the URL …
> Modernize Youtube embeds and exempt from Bleach cleaning, abandon Imgur embeds

- KerbalStuff/app.py
- config.ini.example
- templates/game.html
- templates/layout.html
- templates/mod.html
- templates/mod_list.html
- templates/view_profile.html
Started working on this yesterday, and funnily enough today @V1TA5 suggested it in the Discord.
This pull request adds HTML meta tags according to the [Open Graph protocol](https://ogp.me/) to SpaceDock.
These tags are used by websites and programs to generate "embeds" / "cards" / previews of a shared link.
Among those are Discord, Facebook and Element (Matrix client).
Twitter requires their own custom meta tags, AFAIK. We can think about adding them too, once we've confirmed this works as intended.
Open Graph only defines the _declaration_ of meta tags, it does not define how they should be interpreted, used and rendered. This means that every software/service shows them a bit differently.
Right now there already is a single Open Graph tag present, which sets an image to display in the …
> Add OpenGraph meta tags

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/profile.py
- frontend/coffee/edit_pack.coffee
While we worked on #384, I also created a mod with a name that contains valid HTML with valid JavaScript.
I was relieved that I didn't find any place where this JavaScript is executed, it looked like we / the browser correctly escapes it everywhere (it does so inside header tags like `<h1>` for example).
Well, now I was looking at #380 and trying it out, and it turns out that the typeahead library does not escape HTML in its preview drop down:
You could argue this is a bug in the library, and they did actually fix it in release 0.11.0 (we're at 0.10.2):
- https://github.com/twitter/typeahead.js/issues/964
- https://github.com/twitter/typeahead.js/pull/1182
But at the same time I'd argue that our API (or at least the frontend that consumes it) should do sanitization as well. After asking …
> Escape mod name in mod pack typeahead

- frontend/static/css/bootstrap-theme.css
The hamburger dropdown menu lacks a background on mobile, making it non-usable:
One of the Bootstrap stylesheets has a directive to make the menu background transparent on mobile:
However, this is not a real part of the Bootstrap project; see 75c918d76f21505c6c9ba47650213376431739d7, it was added by @V1TA5 in an attempt to fix something about the menu on mobile (but I'm not able to find any documentation of _what_ it was trying to fix). The resulting problem was pointed out a few days later in https://github.com/KSP-SpaceDock/SpaceDock/issues/145#issuecomment-208120923, but no one seems to have connected it to that change or investigated it at the time.
Now the transparent background directive is removed, so the menu looks right:
Fixes #391.
> Fix mobile menu background

- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/admin.py
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/blog.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/blueprints/profile.py
- templates/mod.html
If you edit a mod and save your changes, a `ga=<Game+3102+'Kerbal+Space+Program'>` parameter is appended to the URL. This parameter is not needed for that URL, and these stray parameters are sometimes seen [pasted into the forum](https://forum.kerbalspaceprogram.com/index.php?/search/&q=Game%2B3102&quick=1) or CKAN:
The `ga` parameter is passed to `url_for()`, and since the game isn't a parameter to the `/mod/` route, it is appended to the end of the URL:
https://github.com/KSP-SpaceDock/SpaceDock/blob/4054e8eb0b09b51289b503256dbe3d0d01321dae/KerbalStuff/blueprints/mods.py#L322
https://github.com/KSP-SpaceDock/SpaceDock/blob/4054e8eb0b09b51289b503256dbe3d0d01321dae/KerbalStuff/blueprints/mods.py#L101-L104
The format of the value comes from `Game.__repr__()`: …
> Remove ga parameter from post-action mod URLs

- KerbalStuff/blueprints/mods.py
- frontend/coffee/global.coffee
- frontend/styles/listing.scss
- frontend/styles/mod.scss
- templates/layout.html
- templates/mod-box.html
- templates/mod.html
I've wanted to rework the very janky follow/unfollow buttons since KSP-SpaceDock/SpaceDock#343, but that pull request had a lot of other things going on and I did not want to increase its scope. KSP-SpaceDock/SpaceDock#379 focused exclusively on the follow buttons, and this pull request replaces that one.
Too much of the visual and style info about the follow/unfollow buttons has been encoded into client script code. The `click` event handler manipulates the text, tooltips, glyphicon classes, etc., to transform a follow button into an unfollow button and vice versa. This essentially means the client script code needs to know everything about how these buttons are supposed to appear, which is hard to maintain and prone to bugs.
- Trying to unfollow returns
```
500 Internal Server Error: …
```
> Fix follow buttons

- README.md
- build-frontend.sh
- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
We are currently on NodeJS 10 from Ubuntu's default repositories, which is EOL since quite some time.
There is one dependency, node-sass, whose latest release no longer supports Node 10. This latest release updates some dependencies that Dependabot currently reports "security vulnerabilities" for. See #386
We currently run `npm install` to install all our frontend dependencies, both inside the Docker container and bare metal deployment. `npm install` however can make changes to `package-lock.json`, and if it does, it breaks later deployments because they abort if the repo is dirty.
On Discord we have decided to go with NodeJS 16, which is the CURRENT release and conveniently LTS as well, and receives updates until 2024-04-30.
The docker image is changed to node:16 as base.
`node-sass` is …
> Update to NodeJS 16 & run npm ci on deployment

- KerbalStuff/ckan.py
When adding a new mod to CKAN, the repo link can help us find useful information. Currently it's not included in the PR, so we have to click it from the mod's SpaceDock page.
See KSP-CKAN/NetKAN#8780 for a typical example.
Now the payload sent to CKAN to make those PRs includes a new `source_link` value containing the source code URL. KSP-CKAN/NetKAN-Infra#227 will add this to the PR body near the homepage.
> Send source link to CKAN

- KerbalStuff/common.py
This link to a modpack on beta throws a 500: https://beta.spacedock.info/pack/1/some%20stuff
```
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/../templates/layout.html", line 10, in top-level template code
{%- block opengraph %}
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/../templates/mod_list.html", line 9, in block "opengraph"
<meta property="og:description" content="{{ mod_list.description | first_paragraphs | bleach }}">
File "/var/www/virtual/spacedock.info/htdocs/SpaceDock/KerbalStuff/common.py", line 46, in first_paragraphs
return '\n\n'.join(PARAGRAPH_PATTERN.split(text)[0:3])
TypeError: expected string or bytes-like object
```
#385 made use of our `first_paragraphs()` function to get a short-ish text that can be put into tne …
> Handle null text in first_paragraphs()

- KerbalStuff/blueprints/mods.py
- requirements-backend.txt
SpaceDock keeps track of how many times each mod has been downloaded. These numbers are displayed and used to determine the mod's score.
The download counts include requests by self-identified bots, software that does not reflect user interest or choice. This distorts the download counts.
(Currently CKAN's bots are not identifying themselves as bots, but we are going to move towards doing that, see KSP-CKAN/CKAN#3490 and KSP-CKAN/xKAN-meta_testing#84.)
If you paste a link into Discord, Discord retrieves the link and parses its HTML to find OpenGraph tags to display in the chat (see #385). For SpaceDock download links, this currently only works if there is a space in the mod name, because Discord excludes the `/download` suffix from the URL and retrieves the mod page instead by …
> Downloads: Don't count from bots, send HTML to Discord

- KerbalStuff/app.py
- KerbalStuff/blueprints/login_oauth.py
- KerbalStuff/common.py
- KerbalStuff/database.py
- KerbalStuff/kerbdown.py
- KerbalStuff/stubs/jinja2.pyi
- alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
- alembic/versions/2020_07_20_19_00_00-73c9d707134b.py
- alembic/versions/2021_06_28_19_00_00-17fbd4ff8193.py
- requirements-backend.txt
- requirements-tests.txt
- spacedock
- tests/fixtures/fake_config.py
- tests/test_api_browse.py
- tests/test_api_errors.py
- tests/test_api_mod.py
- tests/test_errors.py
- tests/test_version.py
After #440 was merged, alpha is no longer working (despite working fine in localhost testing).
@DasSkelett says this is caused by pallets/markupsafe#282, which says "You are using an unsupported version of Jinja," meaning that we should use the latest version of Jinja.
In #353 we pinned the Flask and Jinja2 dependency versions because there are API changes that would break parts of the backend and more testing is required.
Backend logs (including deprecation warnings) can be printed with:
```
docker logs spacedock_backend_1 
```
See python/typeshed#5423, the type stubs for Flask and Jinja2 may be removed from typeshed soon because the latest versions of those modules have type hints built-in. I'm not certain, but I think this means we might wake up one day to find that our code using the …
> Upgrade to Flask 2

- KerbalStuff/blueprints/api.py
- api.md
CKAN queries SpaceDock for download counts every day. Currently this happens via the `/api/mod/<mod_id>` route, which means that for each SpaceDock mod that CKAN knows about, we do:
- One HTTPS request with a lot of extra output that isn't needed
- One SQL request with a lot of data sent that isn't needed
This isn't a big problem today, but it is mildly wasteful of resources that could otherwise be available for users.
Now a new `/api/download_counts` route is available that takes multiple `mod_id` form parameters as input, then runs one SQL query that returns the download counts for all the mods without extraneous info and returns them as one JSON object.
To test locally:
```
curl -d 'mod_id=1&mod_id=2&mod_id=3' http://localhost:5080/api/download_counts
```
Once this is live, …
> Batch retrieval of download counts with /api/download_counts

- templates/mod.html
- templates/mod_list.html
- templates/view_profile.html
- https://spacedock.info/pack/397/Cuinq
- https://spacedock.info/mod/1967 still crashes
- We need to handle HTML attribute values specially:
- https://bleach.readthedocs.io/en/latest/clean.html
> If you need to use the output of bleach.clean() in an HTML attribute, you need to pass it through your template library’s escape function. For example, Jinja2’s escape or django.utils.html.escape or something like that.
- https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.escape
- Apparently `ChainedUndefined` (see #378) makes properties safe but not methods, and #385 added `latest.created.strftime()`
- Now the Jinja2 `escape` filter is applied to each instance of user-edited text in the `og:` meta tags, which will prevent them from terminating the attributes. `bleach` was …
> Escape user-edited fields in OpenGraph meta tags

- api.md
```
$ curl --help all
[...]
-b, --cookie <data|filename>  Send cookies from string/file
-c, --cookie-jar <filename>  Write cookies to <filename> after operation
[...]
```
More simply, `-c` creates a cookie file (as when logging in), and `-b` reads from it (as when using established credentials to do things).
All of the `curl` commands in the API doc currently use `-c`, but two of them should be reading the file rather than creating it.
https://forum.kerbalspaceprogram.com/index.php?/topic/170865-spacedockinfo-mod-hosting-site/&do=findComment&comment=4101102
Now the login call uses `-c`, and the mod creation/update calls use `-b`.
> Fix curl commands in API doc

- docker-compose.yml
- start-server.sh
I alternate between Ubuntu and Win7, and previously I could only run a local SpaceDock dev server on Ubuntu. This meant anytime I was in Windows, I had to defer most investigation and testing until after my next reboot into Ubuntu.
Bash provides environment variable `$OSTYPE` so scripts can tell what OS they're on, for details see dylanaraps/neofetch#433. On my system it is `msys` because I'm using MINGW64.
OS | How to install Docker
:-- | :--
Win10+ | Docker Desktop: <https://docs.docker.com/desktop/windows/install/>
Win7 | Docker Toolbox: <https://github.com/docker-archive/toolbox/releases/latest>
I had to use this URL to access the test server on Windows: <http://192.168.99.100:5080/>
The startup script assumes commands that don't exist on Windows:
```
$ ./start-server.sh …
```
> Make ./start-server.sh work on Windows

- frontend/coffee/create.coffee
- frontend/coffee/update.coffee
- frontend/package-lock.json
- frontend/package.json
- Uploads are timing out if they take more than 30 seconds to upload a 2 MiB chunk
- Errors from Dropzone (such as a timeout) are being reported as if a field was missing
- Dropzone implemented a default 30-second timeout per chunk in an older version, which SpaceDock is still using (see dropzone/dropzone#1942), which is ironic because we started using Dropzone in the first place to _avoid_ such timeouts
- Our error handler only looks for `errorMessage.reason` because that's what our JSON-based API calls use, but when Dropzone itself needs to report an error (such as a timeout), it doesn't know about that format, so it just passes a string
- Now we are updated to the latest stable Dropzone, which doesn't time out by default
- Now we check whether `errorMessage` is a string, or if it has a …
> Update Dropzone, display upload errors correctly

- KerbalStuff/blueprints/api.py
https://github.com/andrew-vant/dragalt/releases
https://spacedock.info/mod/1077/Draggable%20Altimeter#changelog
Apparently @andrew-vant entered `v1.0.1+2` there, and SpaceDock silently dropped the `+`. This is bad; user input should be used as-is whenever possible, and if it can't be, there should be a good reason for it, and the input should be rejected with a meaningful error message rather than silently altered.
The user-entered version number is filtered through `secure_filename` before being committed to the db. The specific code that does this has been through a number of mutations and iterations, but the behavior goes all the way back to the beginning.
The reason for this was probably that the download path had to be constructed on the fly based on the mod name and version number. …
> Use mod version entered by user unaltered

- KerbalStuff/search.py
- frontend/coffee/global.coffee
- frontend/styles/navigation.scss
- templates/browse-list.html
- templates/layout.html
- Currently you can't search for a string that contains a space
- Currently you can't exclude a term from a search
- If you want to search by game, you have to know its id number in the db, and attempting to search by a `game:string` value throws a 500 server error
- The `ver:` search term only supports exact matches on the full version string, so you have to type it many times to match larger version ranges
- The advanced search tips are not visible when you start typing your first search, instead you have to submit the search and then notice that there's an "Advanced Search" button, then click that button, and _then_ you can see the tips, but you have to dismiss them again to actually enter your search, so you can't easily double check what you want to search for
- The search box allows …
> Quoted and negated search terms, up front search help

- KerbalStuff/antivirus.py
- KerbalStuff/blueprints/api.py
- config.ini.example
- docker-compose.yml
- requirements-backend.txt
See #404, we should scan user-uploaded files for malware. There previously was a nightly storage-wide scan, but it did not detect the EICAR file and so probably wasn't working correctly.
Now if you set these settings to the location of a running `clamd` instance that can access the storage in your `config.ini` using the same absolute paths as the backend:
```ini
clamav-host=clamav
clamav-port=3310
clamav-quarantine-folder=/storage/quarantine
```
... then we use it to scan:
- Mod version ZIPs at upload
- Background images (just in case)
If a user is caught attempting to upload malware, the upload will fail, the file will be deleted, and all of that user's mods will be locked automatically with the lock reason "Malware detected in upload." After #419, admins will be able to find these mods …
> Scan uploads with pyclamd

- KerbalStuff/blueprints/api.py
- api.md
This is tying up some loose ends from #466.
- The `game_version` filter is renamed `game_version_id` to indicate that it accepts a game database id, not a friendly string
- A new `game_version` filter is added that _does_ accept a friendly string (like "1.12.5")
- The API documentation is updated to reflect the changes from both PRs
> Add browse filters to api doc, filter by friendly game version

- KerbalStuff/blueprints/profile.py
The server recently had to be restarted with lots of this in the log:
```
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(10000)
```
The database only allows 10000 characters for user descriptions.
https://github.com/KSP-SpaceDock/SpaceDock/blob/dbd67221961376193983028c8977c51b5296204d/KerbalStuff/objects.py#L69
But the Python code just passes whatever it receives, and some spammer tried to create a user description that was too long. Somehow this seems to have confused gunicorn into repeating the attempt and taking up lots of CPU. Auto retry somehow?
Now the profile save code check the lengths of the inputs before using them, and if any exceeds their limits, it aborts. Similar to a side fix in #357 for mod editing.
Fixes #469.
> Check user profile field lengths

- templates/login.html
- templates/register.html
Complaints about the `/register` template:
- The text fields are _huge_, way bigger than any conceivable values that might populate them
- The buttons are tiny
- The labels don't have colons
- There's a stray `OR` at the bottom
Complaints about the `/login` template:
- The text fields are _huge_, way bigger than any conceivable values that might populate them
- The buttons are tiny
- The labels don't have colons
- The checkbox isn't aligned with the fields
- There's no link to the support email
> Clean up login/register layout

- frontend/styles/stylesheet.scss
- templates/admin-page-nav.html
On the admin pages there are some number and arrow buttons to jump to different pages of the lists:
These buttons have some quirks that make them mildly annoying in practice:
- They're very close to the profilings list and farther from the border above them
- At the start of the list 7 number buttons are shown, in the middle it is 10, at the end it is 4
- The arrow buttons appear and disappear based on whether they're needed, which makes sense in a way, but can be disruptive if you're actively working on the list and don't expect all your numbers to shift back and forth
- They're dynamically sized, so the first page's buttons are smaller than the last page's and in between they vary based on how big the numbers are
- Now they're moved up by 10px
- Now for we always show the same number of …
> Admin pagination usability fixes

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/blueprints/profile.py
- KerbalStuff/objects.py
- KerbalStuff/search.py
- frontend/coffee/edit_mod.coffee
- templates/edit_mod.html
While editing a mod's co-authors list:
- If you type a user name that doesn't exist and click Add, a blank red box appears
- If you invite a co-author and then later change your mind, you can only remove them if they've accepted, otherwise you have to wait till they accept
- If you edit a mod with pending co-author invitations, they will say "(pending)", but if you freshly invite a new co-author, it won't say "(pending)" until you reload the page
Co-authored mods (where you're not the primary author but have received and accepted an invitation to co-author) are missing from:
- The user profile
- `/api/user/<username>`
- `/api/search/user?query=<username>`
- Searches for `user:<username>`
Since some co-authors are really the new primary maintainers, this can be misleading.
The "view your …
> Co-authorship fixes

- templates/mod.html
- The descriptions on the mod page are very wide on a wide screen, which is not a good use of that space since your eye has to trace very far to read from the end of one line to the beginning of the next:
- Source code links on the mod page can be "cut off" if they are too long, which does not seem necessary given the available space:
- Now if the browser window is 1200px or wider (which Bootstrap defines as `lg`, the largest scale that it recognizes), the information/changelog/stats tabs and their contents appear at the right instead of the bottom, so we take advantage of wide screens and make the description text easier to read
- Now source code links will wrap beneath their label instead of being cut off
Fixes #390.
> Widescreen layout for mod page

- frontend/static/css/bootstrap-theme.css
- frontend/styles/navigation.scss
- templates/layout.html
- The search box is positioned weirdly for logged out users, floating in space off to the right:
For logged in users it is not visible (and Log Out is missing too):
... unless you scroll down, when it is revealed to also be floating in space to the right:
- The menu items are inconsistent for the two groups of users (donate before random vs. donate after blog; donate opens a new window in one case but not the other)
- There are some subtle inconsistencies regarding when various styles switch from desktop to mobile
- The placeholder text in the search box is oddly bright, usually this is a dimmer color than a real text value to de-emphasize it
- Bootstrap sets the max height of `.navbar-fixed-top .navbar-collapse` to 340px, which is smaller than our menu
- `bootstrap-theme.css` was …
> Fix mobile hamburger menu and search

- templates/browse-list.html
Searches only return one page (30 mods):
- https://spacedock.info/search?query=space
- https://spacedock.info/kerbal-space-program/search?query=space
If you're searching for a common term, the mod you want may not be on the first page, but there's no obvious way to view more pages. If you manually add a `&page=` parameter to a search URL, the backend route supports pagination already:
- https://spacedock.info/kerbal-space-program/search?query=space&page=2
- https://spacedock.info/kerbal-space-program/search?query=space&page=3
- https://spacedock.info/kerbal-space-program/search?query=space&page=4
Since this pull request was submitted, two users on the SpaceDock forum thread have requested it.
The `browse-list.html` template has two `{#  TODO #}` blocks where search pagination should be: …
> Paginated search buttons

- KerbalStuff/ckan.py
KSP-CKAN/NetKAN#8872 was originally submitted with no homepage or source code links, but both existed. I found them via the links on the author's profile.
Later, KSP-CKAN/NetKAN#8918 was submitted when a new co-author checked the CKAN box, but only the original author was included in the description.
Now the new mod notification to CKAN contains the author's GitHub and forum info, as well as all of the same fields for each co-author in a `shared_authors` array. A future PR in NetKAN-Infra can then add them to the pull request body to make it easier to find all the info.
A `download_size` property is added as well, pulled from the default mod version if available. This way a CKAN reviewer with a slow network or full disk can defer reviewing huge mods until he or she is at a computer able …
> Send download size, co-authors, and authors' GitHub and forum names to CKAN

- KerbalStuff/app.py
- KerbalStuff/kerbdown.py
- requirements-backend.txt
- templates/markdown.html
On GitHub, the KSP forum, and most other web sites with users and comments, you can use an @-username sequence to link to a user of that site.
Currently this doesn't do anything on SpaceDock. It could be useful if you want to credit a user for something or if their mods are relevant to your mod's description.
(Thought of while reviewing KSP-CKAN/NetKAN#9007, which accidentally passed such a string through to a pull request and notified the wrong user on GitHub. The link in [that description](https://spacedock.info/mod/2978/YnoT1300) still won't be valid because it references a user that exists on the forum but not SpaceDock, but it would still be a nice feature to have for other cases.)
Similarly, GitHub supports `:emoji_name:` syntax for inserting emojis, as in:
`:thinking:` → :thinking: …
> Parse @username links and colon emoji codes in markdown

- KerbalStuff/blueprints/api.py
In the KSP modding ecosystem, you need four things for a truly complete setup:
- Hosting page
- Download link
- Home page
- Remote version file link so KSP-AVC can check for new releases
Currently SpaceDock is great for the first two, and the forum is typical for the third.
Remote version files commonly are hosted on:
- ksp-avc.cybutek.net (the original KSP-AVC host)
- GitHub
- ksp.spacetux.net (for @linuxgurugamer's mods)
It's even more common for SpaceDock mods to lack remote version files entirely. When this is the case, KSP-AVC users will not receive notifications when new versions are available.
If a mod author wants to host a mod on SpaceDock and include a version file with a `URL` property so KSP-AVC can alert users for new versions, they have to create an entry on …
> API route for auto-generated remote version files

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/purge.py
- frontend/coffee/mods.coffee
- frontend/styles/mod.scss
- templates/mod.html
Sometimes some mod authors build their mods incorrectly and then upload them to SpaceDock without checking them. Currently the remedy for this would be to delete that mod version and then create it again, which is a lot of steps, and I don't think you can do that when there's only one version.
Now the version editing popup has a Dropzone control:
If the user doesn't select a new file, then clicking Save Edit will update the changelog and leave the download as it is.
If the user uses this field to select a new ZIP, then clicking Save Edit will upload it as a replacement for the current file:
1. The old file is deleted from storage
2. A `PURGE` is sent to the CDN to purge the old file from the download cache (see #313)
3. The new file is saved to the path where the old file used to be
4. …
> Allow mod authors to replace downloads

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/common.py
- KerbalStuff/objects.py
- alembic/versions/2021_10_27_20_24_54-1b3f98f3620d.py
- frontend/coffee/mods.coffee
- templates/mod.html
- templates/mod_changelog.html
See #402, mods with a lot of changelogs load more slowly than other mods, even if the user never looks at them, because we render them all from Markdown to HTML during page load.
- The mod changelog is split into a separate `/mod_changelog/<mod_id>` route and template
- The mod page loads without the changelog initially, so all mods should load fast
- If the user clicks the Changelog button (probably rare), we load the full list of changelogs on demand and insert it into the page
- A new `ModVersion.changelog_html` column now holds the rendered content of a version's changelog, stored at creation and edit, and also populated on demand at load if needed (to avoid needing to run a migration that could take a long time)
Fixes #402.
> Deferred loading and pre-rendering for mod changelogs

- KerbalStuff/app.py
- KerbalStuff/blueprints/admin.py
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/common.py
- KerbalStuff/objects.py
- KerbalStuff/search.py
- alembic/versions/2021_10_28_10_32_09-44040211d4e7.py
Despite #370, some `/download/` routes are still taking up to 3 seconds, and most of it seems to be spent in the `DownloadEvent` SQL query:
https://use-the-index-luke.com/sql/sorting-grouping/indexed-order-by
> SQL queries with an order by clause do not need to sort the result explicitly if the relevant index already delivers the rows in the required order.
The `(version_id, created)` index was supposed to speed up this query, but it does not deliver the rows in the required order! The query is descending order, while the index is ascending. (I was familiar with bidirectional indexes only and so did not realize this was a consideration.)
https://github.com/KSP-SpaceDock/SpaceDock/blob/4dee33b09072e018cd3f47954f9393a153e55eef/KerbalStuff/blueprints/mods.py#L569-L572
I think this means that …
> Fix downloads performance

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/common.py
- KerbalStuff/objects.py
- KerbalStuff/thumbnail.py
- alembic/versions/2021_11_04_12_36_53-beb0f0da734e.py
- alembic/versions/alembic.pyi
- frontend/coffee/edit_pack.coffee
- templates/edit_list.html
- templates/mod_list.html
- templates/pack-box.html
If you edit a modpack, there's a link to upload a background, but it doesn't work. Hence no modpacks have backgrounds or thumbnails.
The upload link references some very old code based on `MediaCrush`, which SpaceDock doesn't include, so it just crashes.
Now the modpack uploading link works, and modpack backgrounds and thumbnails are displayed.
- The `ModList.background` column is increased from 32 to 512 characters to match the other background columns
- The `ModList.thumbnail` column is created
- The recent background/thumbnail handling fixes are copied to `ModList`
If a user gives a modpack the same name as another of his or her own mods or modpacks, the backgrounds and thumbnails may end up in the same `username_userid/packname` folder in storage. This should be fine, though, because …
> Fix modpack backgrounds and thumbnails

- KerbalStuff/blueprints/admin.py
- KerbalStuff/objects.py
- alembic/versions/2023_03_03_22_00_00-76ba7330ce15.py
- templates/admin-locked-mods.html
- templates/admin.html
See #403, locked mods are only visible to admins, but admins don't have any easy way to find them if they don't already know about them. This could be a problem if we ever write code that locks mods automatically (e.g., anti-virus scanning), or if we just forget about a mod that we meant to check up on.
Now the admin pages have a Locked Mods tab between Game Versions and Blog. It shows the locked mods in the style of the usual "mod box" listings, 30 per page, using a new multi-column index of `(Mod.locked, Mod.updated.desc())` so if a user edits a mod, it will pop to the beginning of the list. The lock reason is not shown in the list on the assumption that admins will click the mods to view it.
Fixes #403.
> Add Locked Mods tab to admin pages

- KerbalStuff/app.py
- KerbalStuff/blueprints/blog.py
- KerbalStuff/objects.py
- alembic/versions/2023_03_03_22_10_00-3a9de8cf341d.py
- templates/admin-blog.html
- templates/edit_blog.html
See #406, sometimes we want to prepare an announcement but are not ready to publish it yet. It would be nice to be able to save our work and publish it later.
- A new `BlogPost.draft` column is created and set to false for all existing rows
- A Draft checkbox is added to blog post creation and editing corresponding to the new column
- Only admins see drafts in the blog listing
- Drafts are never shown as announcements
- Users attempting to bypass the blog listing filters by guessing id numbers in the URL to see members only posts will no longer succeed
Fixes #406.
> Non-public draft blog posts

- KerbalStuff/celery.py
- KerbalStuff/email.py
- frontend/coffee/mods.coffee
- frontend/coffee/update.coffee
- templates/edit_mod.html
- templates/email-everyone.html
- templates/email-mod-autoupdated.html
- templates/email-mod-updated.html
- templates/mod.html
Mod changelogs are in Markdown format and rendered into HTML for the mod page. But when a mod is updated, the email notification to followers is in plain text format only, and the changelog appears in plain text Markdown. Some authors may wish their Markdown to be rendered in a nicer format.
https://docs.python.org/3/library/email-examples.html
Similarly, the Email tab in the admin pages allows a mass email to be composed to all users or all authors, and it has the Markdown rich text editing controls enabled, but the email is sent in plain text.
Now update emails are in MIME multipart format, with a `plain` part containing the old plain text message and an `html` part generated by a simple Jinja2 template that puts the changelog through our familiar ` | markdown | bleach` pipeline. The …
> HTML emails

- KerbalStuff/app.py
- KerbalStuff/middleware/profiler.py
- config.ini.example
See #409, with the merging of #414 and #416, all remaining known causes of responses slower than 300ms should be addressed. Once that is the case, it will be very boring and mostly useless to have a long list of randomly sampled responses in the 10–150ms range that do not need attention. If there are any routes left that are still slow, it will be rare for them to be randomly selected for profiling. We would need a different way to collect data to catch such responses.
Now if you set this in `config.ini` (recommended!):
```ini
profile-threshold-ms=250
```
... then instead of randomly selecting a small fraction of responses for profiling, we will profile _all_ responses but only save data for the ones that take longer than the configured time. (If you set both `profile-threshold-ms` and …
> Option to profile everything, save data only for slow responses

- frontend/styles/listing.scss
- templates/mod-box.html
Now locked mods have a 🔒 icon in listings (in which they're only visible to admins):
Fixes #474.
> Lock icon for locked mods

- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/objects.py
- KerbalStuff/thumbnail.py
- alembic/versions/2023_03_14_18_49_21-b9e4c97b74c1.py
- frontend/coffee/game.coffee
- templates/game.html
With the addition of KSP2, SpaceDock now has another game listed with a similar name, so the usability of the list of games has become more important. See #477 for some previous clean-up of that list.
There is some support for game header images in the database, but none in the code. It would be nice to have this to make it easier to spot the game that interests you in the game list.
Now the existing support for profile and mod header images is applies to games.
- A `Game.thumbnail` column is created
- Admins can see a "Click to upload header" link when viewing the main page for a game
- If used, the link populates `Game.background` and `Game.thumbnail`
- If populated, `Game.background` appears across the top of a game's page
- If populated, `Game.thumbnail` is used for the game's entry …
>  Game thumbnails

- KerbalStuff/celery.py
- KerbalStuff/ckan.py
- config.ini.example
This extends the work from #294 to cover KSP2.
- <https://github.com/KSP-CKAN/KSP2-CKAN-meta/blob/main/builds.json>
Enable with configuration:
```ini
ksp2-game-id = 12345
```
> Auto-import KSP2 versions from CKAN

- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/objects.py
- alembic/versions/2023_03_20_12_00_00-7eec82634342.py
- alembic/versions/alembic.pyi
- frontend/coffee/profile.coffee
- templates/profile.html
- templates/view_profile.html
Every now and then users want to delete their accounts (we should ask for the reason the next time, out of interest).
Every website with the option to create accounts should (and also must) have another option to delete these accounts again.
There's still the discussion on what we actually want to delete if a user deletes their account.
For know, to get us started, I decided to stay consistent with what we already do and delete everything linked to that user, both in the database and on disk. This means mods of these users are deleted too.
Please continue this discussion in #215 or on the Discord and leave the comments on this PR to actual code review.
I'll update this PR depending on how we decide on that.
* If the user's session cookie has an invalid game id (e.g. if the game has been …
> [WIP] Add cascade delete constraints, allow users to delete their accounts

- KerbalStuff/blueprints/admin.py
- frontend/coffee/admin-users.coffee
- templates/admin-users.html
See #413; the admin user list has several annoying layout quirks and doesn't allow the main operation I want to do there: deleting spam users.
- Each column of the users table is now a static width, the contents do not overflow onto neighboring cells, and the email and forum cells may be hovered to view the full text in a tooltip
- The username cells now have Delete buttons that show a confirmation prompt when clicked, and if you confirm that you really want to delete, the user is deleted and the list is refreshed
Note that since this is intended for nuisance users who aren't really users of the site, it does not do anything to clean up mods created by the user. It just deletes the user.
- The created column no longer displays seconds or milliseconds
- The public and admin columns are …
> Admin users list usability, buttons to delete users

- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/search.py
- templates/browse-list.html
SpaceDock has three main ways of sorting mod lists:
- Highest score at top
- Most recently created at top
- Most recently updated at top
When you perform a text search, the sort is only by score.
It's not easy to tell that this is how it works, and it's even less easy to switch between different sorts; you have to go back to the game's main page and click a different link.
It's desirable to be able to tell what the current sort is and change it.
Additional sort methods for searching could be useful.
- Now mod lists using one of those three sorts contain a sorting control in the upper right that indicates the current sort and allows the user to switch to the others:
- To make this fit nicely on the screen, the RSS icon in the page header is now the same height as the text so the header …
> Easier sorting

- KerbalStuff/blueprints/mods.py
@BrettRyland reported on Discord that he couldn't edit the changelog entries for this mod:
- <https://spacedock.info/mod/2487/BDArmory%20Plus>
This mod was editable for him though:
- <https://spacedock.info/mod/2657/Camera%20Tools%20continued>
In one case, the user is the main author, in the other a co-author.
As of #414, the co-author check is missing from the new `/mod_changelog` route:
https://github.com/KSP-SpaceDock/SpaceDock/blob/af016ae8f28e8cf320363741b90cc40cd31e6f86/KerbalStuff/blueprints/mods.py#L209-L217
Previously `editable` would have been set to `True` during the `/mod` route's loop to add the co-authors to the display.
Now we use `mod_check_editable` to determine editability, which handles co-authors.
> Fix changelog editing for co-authors

- KerbalStuff/notification.py
- KerbalStuff/objects.py
See KSP-CKAN/NetKAN-Infra#293 and KSP-CKAN/NetKAN-Infra#294, the `shared_authors` property sent to CKAN just says `username`, so we can't use it to add the co-authors to pull requests.
#435 was mis-guided; I thought the data sent to CKAN was in JSON format, but it's in POST form input format, which means it can only handle strings and lists of strings, not more complex data structures. That PR tried to send a list of dicts in the `shared_authors` property, which can't work.
- Now `shared_authors` is no longer sent
- Now `Mod.all_authors` provides the main author and all the co-authors for convenience
- Now these POST form inputs are lists with one element per (co-)author:
- `username`
- `user_github`
- `user_forum_id`
- `user_forum_username`
- `email`
- `user_url` (which was missed in …
> Send co-authors to CKAN as POST form lists

- KerbalStuff/objects.py
- templates/admin-notifications.html
It would be nice to have a sense of how many mods are CKAN-enabled in the admin pages.
Now the mod count appears in parentheses:
This is done via an sqlalchemy `count()` call to ensure the db won't send the whole list back.
> Show how many mods use each notification

- KerbalStuff/blueprints/admin.py
- templates/admin-users.html
1. Go to the admin pages user list
2. Search the users by some keyword such as "escort" or "callgirl"
3. Delete a user
4. The search resets, so you're back to the list of all users. This is inconvenient for deleting many users from the same search; you have to re-enter the search every time.
Now after you delete a user from the admin user list, any search query you may have entered remains active, so mass-deleting spammers will be easier.
> Preserve admin user search after user deletion

- KerbalStuff/blueprints/api.py
- frontend/coffee/profile.coffee
- templates/view_profile.html
As of #316, the user profile page now has a "Delete user" button for admins, which opens a confirmation dialog:
However, no matter what you do, the "Delete account" button in the confirmation popup doesn't work. The call to the server never happens.
Since the profile editing page has a rich text box, and the `profile.coffee`/`profile.js` client file is shared between the profile editing page and the profile viewing page, the rich text editor tries to initialize on page load and throws an exception because there are no `textarea`s, just like in 1e130afadd510f081db1026070f0d58bc508cf6f.
This exception then stops the client code initialization, so the hooks that make the popup work are not set up.
- Now we only try to load the rich text editor if we have a `textarea` for it to use. This will …
> Fix admin user deletion on profile

- KerbalStuff/blueprints/anonymous.py
- templates/game.html
Currently Kitbash Model Club's page is empty because there are no mods for it, which looks like an error to any user wandering in there:
- <https://spacedock.info/Kitbash-Model-Club>
Games with no mods were hidden from the front page in #477 and restored in 707f1afc04028a34989402f744e3f2e39bf739b5, because the team did not agree on the solution.
Now when a game has no mods, we show an explicit explanation instead and a button inviting the user to upload something:
This somewhat addresses the concern about a useless empty page while still keeping newly enabled games visible on the front page.
In addition, we no longer show a link to the list of modpacks if there are no modpacks for that game.
> Show add-mod button instead of empty game sections

- KerbalStuff/notification.py
A game version with an empty version string has been added, then deleted, then added again a couple of times:
We don't know the exact cause of this since there are 2 or 3 different automated sources for this data currently:
- A PHP script by VITAS that accesses the official JNO versions API
- A PHP script by VITAS that parses JNO's blog post titles or something
- The built-in support from #480
However, we can construct a plausible narrative of how it happens: If the API sometimes glitches out and returns an empty string, the built-in support from #480 would add that empty string to the db because it doesn't check it.
However², the alpha and beta servers have both been using this code the same way as production, and neither has had this issue so far, so this explanation is not very likely. …
> Make sure JNO versions aren't empty

- KerbalStuff/common.py
- KerbalStuff/kerbdown.py
- requirements-backend.txt
@TedThompson stopped by the SpaceDock Discord to complain about #426 and also point out that SpaceDock's markdown doesn't support tables, as in:
```
Column 1 | Column 2 | Column 3
:-- | :-- | :--
Cell 4 | Cell 5 | Cell 6
```
Apparently tables are considered part of [Markdown's "extended syntax"](https://www.markdownguide.org/extended-syntax/#tables), even though most users probably take for granted that they will always be supported. So the Python `markdown` module doesn't enable them by default; you have to use the `tables` extension.
Now if you use Markdown table syntax, it'll render as expected:
- Our Bleach config is updated to allow table-related elements and `style` attributes on table cells (for alignment)
- We use the `tables` extension, but not as shown in the examples, because …
> Support tables in markdown

- frontend/styles/index.scss
This is a completely unused line of code; ```margin-top``` is defined twice, and is overridden, making the top line completely useless.
🤔
> Remove extra margin-top from h3 styles

- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/common.py
- KerbalStuff/objects.py
- alembic/versions/2024_01_02_14_56_29-f5a5d29ec765.py
- frontend/coffee/global.coffee
- frontend/styles/listing.scss
- generate_revision.sh
- templates/browse-list.html
- templates/game.html
- templates/mod-box.html
@cheese3660 has been helping to admin KSP2 and gave some feedback that it would be good to be able to control the ordering of featured mods. Currently the most recently featured mod always sorts to the front of the list, so some reordering could be done by de-featuring and re-featuring mods in the desired order, but that would be extremely cumbersome.
Now left and right chevrons (with explanatory tooltips) can be clicked to move a mod around in the featured list:
On the back end, the `featured` table now has a `priority` column that holds each featured mod's position within the featured list. This is a per-game, non-negative integer that is incremented by the left chevron and decremented by the right chevron. Existing featured mods' priorities will be defaulted based on the current …
> Let admins control ordering of featured mods
