- KerbalStuff/blueprints/accounts.py
- templates/about.html
- templates/browse-list.html
- templates/confirm.html
- templates/create.html
- templates/create_list.html
- templates/edit_list.html
- templates/edit_mod.html
- templates/index.html
- templates/layout.html
- templates/login.html
- templates/markdown.html
- templates/mod.html
- templates/mod_list.html
- templates/privacy.html
- templates/profile.html
- templates/register-oauth.html
- templates/register.html
- templates/view_profile.html
You can undo the registration change when you're ready with the following command:
git revert 2b21bb0
> Disable registration and change name

- KerbalStuff/celery.py
- KerbalStuff/config.py
- config.ini.example
> Added options for using SSL/TLS and SMTP auth

- KerbalStuff/blueprints/accounts.py
- KerbalStuff/config.py
- config.ini.example
Added a way to disable registration properly, fixed boolean parsing and removed spaces / tabs mixups
> Minor bugfixes and enhancements

- README.md
Changes the (safe) references to KS to SpaceDock.
> Change the KS references to SpaceDock where practical

- templates/privacy.html
add language promising a best-effort to notify about site changes, so we can refer people to the terms of use, should we get "but I didn't know!!!!" complaints.
> add language promising a best-effort to notify about site changes.

- KerbalStuff/blueprints/mods.py
- scripts/piwik.js
- templates/create.html
- templates/edit_mod.html
- templates/layout.html
- templates/privacy.html
Added Opt-In for CKAN, even though it is still broken. Also, added Piwik Tracking
> CKAN and Piwik

- KerbalStuff/app.py
- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/admin.py
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/blog.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/login_oauth.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/blueprints/profile.py
- KerbalStuff/email.py
- app.py
- scripts/create.coffee
- scripts/update.coffee
Names are now fully configurable through the config.
> A smarter solution for variable names and last fixes

- KerbalStuff/blueprints/lists.py
- templates/mod_list.html
Currently, Admins and the creator of the pack can delete them.
> Added the ability to delete modpacks

- .dockerignore
- Dockerfile
- README_DOCKERFILE.md
- docker/pb_hba.conf
- docker/start.sh
- docker/start_celery.sh
- docker/supervisord.conf
This should resolve #3 
Would appreciate it if someone could run through the README and the Dockerfile and let me know if I'm doing something strange.
> Created a dockerfile for local development

- KerbalStuff/app.py
- config.ini.example
- templates/layout.html
Resolves #51 - Also makes quick support a bit easier.
> Added a config option to provide a link to an IRC channel

- CONTRIBUTING.md
I also added a bit about the -m flag for commits
> Fixed some spelling in CONTRIBUTING.md

- KerbalStuff/blueprints/blog.py
> Force blog posts to be ordered by date

- KerbalStuff/app.py
- templates/layout.html
Seems strange to have the registration link just redirect back to the home page...
> Don't show registration link if registration is disabled

- KerbalStuff/blueprints/anonymous.py
Every recently published mod would have the 'updated' field set to the publish date, which would display it twice in the homepage: both in recently updated and newly created mods.
It's a hacky way to fix #73. The other method involves messing with SQL and figuring out how to count the versions for each recently updated mod, or have a new field in the Mod object that would count the versions it has.
> Fix a 'bug' that new mods would be listed as updated

- KerbalStuff/celery.py
Closing privacy issue by hiding the "To" field altogether. Just commented out the "To" line. For issue #68 . Not tested.
Fixes #41, Fixes #68
> [proposal] Remove addresses from "To" field, BCC instead + add Precedence header

- KerbalStuff/app.py
- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/admin.py
- KerbalStuff/blueprints/blog.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/login_oauth.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/blueprints/profile.py
As of #198, the `master` branch now has identical code to the production server.
The dev servers are live-ish and are switched to their individual branches:
| Server | Branch |
| --- | --- |
| https://alpha.spacedock.info/ | https://github.com/KSP-SpaceDock/SpaceDock/tree/alpha |
| https://beta.spacedock.info/ | https://github.com/KSP-SpaceDock/SpaceDock/tree/beta |
The `redirect()` calls are hard coded to `spacedock.info`, which prevents them from working on other servers. We need to fix that for the dev servers to work.
There is code to pull changes from GitHub and restart the server when GitHub notifies us of a change. But while it validates the notification against a configurable branch, it still only pulls from `master`, which won't work for the dev servers. They should be pulling …
> Fixes for hosts that are not spacedock.info

- KerbalStuff/blueprints/mods.py
- KerbalStuff/common.py
- templates/mod.html
Not sure if it works, I reworked my original PR (#133) to adapt to the new branch.
Closes #200
> Add version file size indicator

- api.md
and changed kerbalstuff.com to spacedock.info.
> Replaced all instances of Kerbal Stuff with Spacedock in api.md

- KerbalStuff/blueprints/api.py
If mod is unpublished, it's still hidden from anyone, except the owner.
> Allow getting unpublished mods via API

- scripts/update.coffee
> Handle HTTP 500 for version uploads

- templates/view_profile.html
> Fix unpublished mods being displayed on frontend

- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/admin.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/login_oauth.py
- KerbalStuff/objects.py
- spacedock
* Removed __init__ methods from DB Models
* Added User.create_confirmation method
* Converted all relationships to one2many type with backrefs, _fixed many of them in the process_
* As usual, autoformatting and some renaming
This makes ORM models more uniform and thus manageable.
Tested it locally by hand.
Also my next PR for #227 will rely on this one.
> Models refactoring

- frontend/coffee/create.coffee
_rant rant rant rant_
Wait until page is loaded to execute JavaScript that needs the page to be fully loaded.
We'll only see if this fixes the problem after this is merged to alpha, since I don't experience this issue on my local server.
Fix-up of #271
> Tell JS to wait its turn

- .github/workflows/mypy.yml
- .gitignore
- KerbalStuff/app.py
- KerbalStuff/blueprints/accounts.py
- KerbalStuff/blueprints/admin.py
- KerbalStuff/blueprints/anonymous.py
- KerbalStuff/blueprints/api.py
- KerbalStuff/blueprints/blog.py
- KerbalStuff/blueprints/lists.py
- KerbalStuff/blueprints/login_oauth.py
- KerbalStuff/blueprints/mods.py
- KerbalStuff/blueprints/profile.py
- KerbalStuff/celery.py
- KerbalStuff/ckan.py
- KerbalStuff/common.py
- KerbalStuff/config.py
- KerbalStuff/custom_json.py
- KerbalStuff/database.py
- KerbalStuff/email.py
- KerbalStuff/helpers.py
- KerbalStuff/kerbdown.py
- KerbalStuff/network.py
- KerbalStuff/objects.py
- KerbalStuff/search.py
- KerbalStuff/thumbnail.py
- mypy.ini
This is the same as #269 except it uses a branch in the KSP-SpaceDock/SpaceDock repo so the GitHub action will run (we hope!).
Type hints allow us to specify how a function is supposed to be used and catch when it isn't. They're especially helpful when writing new code, as trivial errors such as trying to access `my_dict['prop']` as `my_dict.prop` (my personal bugbear) are caught before run-time, but are also useful if you just need to know what a function returns or what to pass to it. They're a standard part of Python:
- https://www.python.org/dev/peps/pep-0484/
The `mypy` utility uses type hints to perform type checking:
- http://mypy-lang.org/
- A `mypy.ini` file is added to the project root with some convenient defaults
- `.mypy_cache` is now git-ignored
- Type hints are added …
> Add type hints

- alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
```
File "/home/DasSkelett/git/SpaceDock/venv/bin/alembic", line 8, in <module>
sys.exit(main())
File "/GIT/SpaceDock/venv/lib/python3.8/site-packages/alembic/config.py", line 577, in main
CommandLine(prog=prog).main(argv=argv)
File "/GIT/SpaceDock/venv/lib/python3.8/site-packages/alembic/config.py", line 571, in main
self.run_cmd(cfg, options)
File "/GIT/SpaceDock/venv/lib/python3.8/site-packages/alembic/config.py", line 548, in run_cmd
fn(
File "/GIT/SpaceDock/venv/lib/python3.8/site-packages/alembic/command.py", line 448, in heads
heads = script.get_revisions(script.get_heads())
File "/GIT/SpaceDock/venv/lib/python3.8/site-packages/alembic/script/base.py", line 320, in get_heads
return list(self.revision_map.heads)
File …
```
> Copy get_mod_score instead of importing it

- KerbalStuff/blueprints/api.py
> Add game ID filter
